{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Load libraries</h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 191,
   "metadata": {},
   "outputs": [],
   "source": [
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "from shapely import wkt\n",
    "import keplergl\n",
    "from tqdm import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "import h3\n",
    "import re\n",
    "from geopy import Nominatim, location\n",
    "from geopy.extra.rate_limiter import RateLimiter\n",
    "import googlemaps"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Load data: houses pricing, airbnb data and Madrid's districts.</h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 181,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load both datasets\n",
    "data = 'datasets/analyzed_data/clean_after_null_and_outliers_without_boxcox.csv'"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Madrid's districts</h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Axes: >"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYEAAAGsCAYAAAA7axvMAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAClDklEQVR4nOydd3xc1Zn3f/feudO7Rm3UJRfZluVuY8A0O8DGARyc7CZRgBADm43JUpYsr9+Q7EKSNQmbBAKbwOsFEjYQJ2xoCQkJ3RiMLcuWu2XZ6r1M7+2+f4w01mjandE0Sef7+cwHfOfo3jMq5znnKb+H4jiOA4FAIBDmJXSuJ0AgEAiE3EGMAIFAIMxjiBEgEAiEeQwxAgQCgTCPIUaAQCAQ5jHECBAIBMI8hhgBAoFAmMcQI0AgEAjzGGIECAQCYR5DjACBQCDMY+alEdi3bx9uuOEG6PV6UBSF1157Lel7cByH//zP/8SiRYsgEolQVlaGH/7wh+mfLIFAIGQQQa4nkAvsdjtWrFiBr3/967j55ptTusc999yDv/3tb/jP//xPLF++HAaDAQaDIc0zJRAIhMxCzXcBOYqi8Oqrr2Lbtm2ha263G9/5znfw29/+FiaTCQ0NDfjRj36Eq666CgBw5swZNDY24uTJk1i8eHFuJk4gEAhpYF66gxJx991348CBA9i7dy+OHz+OL37xi7j++uvR3t4OAPjjH/+I2tpa/OlPf0JNTQ2qq6txxx13kJMAgUCYdRAjMI2enh48//zzePnll7Fp0ybU1dXhgQcewOWXX47nn38eANDR0YHu7m68/PLLeOGFF/CrX/0KLS0t+MIXvpDj2RMIBEJyzMuYQDxOnDgBv9+PRYsWhV13u90oKCgAAAQCAbjdbrzwwguhcc8++yzWrFmDtrY24iIiEAizBmIEpmGz2cAwDFpaWsAwTNh7crkcAFBaWgqBQBBmKJYsWQIgeJIgRoBAIMwWiBGYxqpVq+D3+zEyMoJNmzZFHXPZZZfB5/PhwoULqKurAwCcO3cOAFBVVZW1uRIIBMJMmZfZQTabDefPnwcQXPR/+tOf4uqrr4ZWq0VlZSW++tWv4uOPP8ZPfvITrFq1CqOjo3j33XfR2NiIrVu3IhAIYN26dZDL5Xj88ccRCASwc+dOKJVK/O1vf8vxpyMQCIQk4OYh77//Pgcg4nXbbbdxHMdxHo+H+973vsdVV1dzLMtypaWl3Oc//3nu+PHjoXv09/dzN998MyeXy7ni4mLua1/7Gjc+Pp6jT0QgEAipMS9PAgQCgUAIQlJECQQCYR5DjACBQCDMY+ZNdlAgEMDAwAAUCgUoisr1dAgEAiHtcBwHq9UKvV4Pmua3x583RmBgYAAVFRW5ngaBQCBknN7eXpSXl/MaO2+MgEKhABD85iiVyhzPhkAgENKPxWJBRUVFaL3jw7wxApMuIKVSSYwAgUCY0yTj8iaBYQKBQJjHECNAIBAI8xhiBAgEAmEeQ4wAgUAgzGNmZAQeffRRUBSFe++9N+aYX/3qV6AoKuwlFovDxnAch+9973soLS2FRCLBli1bQl28JjEYDGhqaoJSqYRarcaOHTtgs9lmMn0CgUCY96RsBJqbm/HMM8+gsbEx4VilUonBwcHQq7u7O+z9H//4x/j5z3+Op59+GgcPHoRMJsN1110Hl8sVGtPU1IRTp07h7bffxp/+9Cfs27cPd911V6rTJxAIBAKQmoqo1WrlFi5cyL399tvclVdeyd1zzz0xxz7//POcSqWK+X4gEOBKSkq4xx57LHTNZDJxIpGI++1vf8txHMedPn2aA8A1NzeHxvzlL3/hKIri+vv7ec3ZbDZzADiz2cxrPIFAIMw2UlnnUjoJ7Ny5E1u3bsWWLVt4jbfZbKiqqkJFRQVuuukmnDp1KvReZ2cnhoaGwu6lUqmwYcMGHDhwAABw4MABqNVqrF27NjRmy5YtoGkaBw8ejPpMt9sNi8US9iIQCARCOEkbgb179+LIkSPYvXs3r/GLFy/Gc889h9dffx2/+c1vEAgEcOmll6Kvrw8AMDQ0BAAoLi4O+7ri4uLQe0NDQygqKgp7XyAQQKvVhsZMZ/fu3VCpVKEXkYwgEAiESJIyAr29vbjnnnvw4osvRgR3Y7Fx40bceuutWLlyJa688kq88sorKCwsxDPPPJPShPmya9cumM3m0Ku3tzejzyMQCITZSFKyES0tLRgZGcHq1atD1/x+P/bt24ennnoKbrc7ojn7dFiWxapVq0LtHUtKSgAAw8PDKC0tDY0bHh7GypUrQ2NGRkbC7uPz+WAwGEJfPx2RSASRSJTMxyMQCIR5R1Ingc2bN+PEiRNobW0NvdauXYumpia0trYmNABA0GicOHEitODX1NSgpKQE7777bmiMxWLBwYMHsXHjRgDB04TJZEJLS0tozHvvvYdAIIANGzYk8xEIBAKBMIWkTgIKhQINDQ1h12QyGQoKCkLXb731VpSVlYViBo888gguueQSLFiwACaTCY899hi6u7txxx13AECozuAHP/gBFi5ciJqaGnz3u9+FXq/Htm3bAABLlizB9ddfjzvvvBNPP/00vF4v7r77bnzpS1+CXq+f6feAQCAQ5i1pVxHt6ekJa2ZgNBpx5513YmhoCBqNBmvWrMEnn3yCpUuXhsb867/+K+x2O+666y6YTCZcfvnleOutt8LiDi+++CLuvvtubN68GTRNY/v27fj5z3+e7ukTCHMel9ePFw/2YEW5Co3laggFRDhgPjNvGs1bLBaoVCqYzWYiJU2YlwQCHJ77uBNPf9iBMZsbACAS0Ni8pAg7r16AZXpVjmdImCmprHPzpp8AgTCf4TgOD71+Ei8d7Am77vYF8OcTQ/jziSHcsEKPx77QCDGbOLZHmDuQcyCBMMfhOA6P/Ol0hAGYzh+PDeCBl49hnjgHCBMQI0AgzHH2Nvfi+Y+7eI390/FBfO/1UwgEiCGYLxB3EIEwx3nz+GBS4//n0254fAHcdmk1aBpoG7KifdiG5eUqXLcsel0OYfZCjACBMId5v20E+8+PJf11vzvci98djqyy/+HnG9C0oSodUyPkCcQdRCDMUUwODx783+NpvecjfzwNl9ef1nsScgsxAgTCHOU//nwGI1Z3Wu/p9gVwot+c1nsScgsxAgTCHORojxG/P9yXkXv/9G/n4PMHMnJvQvYhRoBAmIM8/k574kEpcqBjHE++dz5j9ydkF2IECIQ5xplBCz48N5rRZzy3vxM2ty+jzyBkB2IECIQ5xp59HRl/htXtw++aSY+OuQAxAgTCHMLq8uLNE8nVBaTKf3/UAaPdk5VnETIHMQIEwhzirZNDcPuyE7QdNLvwzRePwEuCxLMaYgQIhDnE4S5jVp93oGMcD/7vcaI3NIshRoBAmENMSkRnk1eO9uPMoDXrzyWkB2IECIQ5RK72424fqSKerRAjQCDMIRaXKLL+TJGAxvIy0pBmtkKMAIEwh7hxRfZ7brt9ARzpMWX9uYT0QIwAgTCHqC9RYGGRPOvPfb9tJOvPJKQHYgQIhDkERVG4pr4o68/9sC2zFcqEzEGMAIEwx6gskGb9mQVyYdafSUgPxAgQCHOMMrUk689cW6XN+jMJ6YEYAQJhDuHw+PCnJNtJpoPXW/vhJ32JZyWkvSSBMEd498wwvvf6KfSbnFl/dseYHXaPD0oxm/VnE2YGMQIEwiwmEOBwpMeI//6oE2+dGsrpXPa3j+Gzy0tzOgdC8hAjQCDMUl5v7cdjf21DnzH7O/9o7HzpCG5aoceqSg2Wl6uwqkINiqJyPS1CAogRIBBmIW1DVvzL74/Bl0d+eI4DXmsdwGutAwCArY2leOrLq4ghyHNIYJhAmGW4fX7c/dKRvDIA0Xjz+GDWehsQUocYAQJhlvFf751H+4gt19PgxQsHunM9BUICiBEgEGYRJ/vN+MUHF3I9Dd4c6jTg7JAl19MgxIEYAQJhluD2+fHAy/kVB+DDAy8fw8l+c66nQYgBMQKEqJwaMGPfuaAeTOeYPcezIXxyfgxffPoAzg7NvuYtJ/st+NyT+3GkJ7tdzwj8INlBhDAcHh9+9UkXHvtrGzgOkAoZNJarsPeujbme2rykpduIn77dho/Pj+d6KjOGVBTnJ8QIEMLw+AJ498wIJlvGOjx+tA1ZcbTHiFWVmtxObh7h9vlx/++P4c0cSEBkApahsEyvzPU0CFGYkTvo0UcfBUVRuPfee3mN37t3LyiKwrZt28KuDw8P42tf+xr0ej2kUimuv/56tLe3h4256qqrQFFU2Osb3/jGTKZPiIJaKsTv/3EjHr5xWeia0eHFPzzzKR54+RjODlkQIDu6jOLxBbDzxaNzxgAAgNfP4ZezKKA9n0jZCDQ3N+OZZ55BY2Mjr/FdXV144IEHsGnTprDrHMdh27Zt6OjowOuvv46jR4+iqqoKW7Zsgd0e7ou+8847MTg4GHr9+Mc/TnX6hDgwNIVbLqmCboo8sMcfwP+29OH6xz/CZT96D70GRw5nOLf5jz+fwTtnhnM9jbTzzL4O0os4D0nJCNhsNjQ1NWHPnj3QaBK7CPx+P5qamvDwww+jtrY27L329nZ8+umn+OUvf4l169Zh8eLF+OUvfwmn04nf/va3YWOlUilKSkpCL6WSHC8zBU1T+PyqsqjvDZpdxAhkCLPDi9819+Z6GhlBrxJDJGByPQ3CNFIyAjt37sTWrVuxZcsWXuMfeeQRFBUVYceOHRHvud1uAIBYLL44KZqGSCTC/v37w8a++OKL0Ol0aGhowK5du+BwxF6I3G43LBZL2IuQHHduqoVQEPkrUq6RYH0N0Y/PBL852A2nd27uli0uHwkO5yFJG4G9e/fiyJEj2L17N6/x+/fvx7PPPos9e/ZEfb++vh6VlZXYtWsXjEYjPB4PfvSjH6Gvrw+Dgxd9ol/5ylfwm9/8Bu+//z527dqF//mf/8FXv/rVmM/dvXs3VCpV6FVRUZHcByWgSCnGl9dFft++dmk1BAzJLk43bp8fv/qkK9fTyBgGuyeUdkzIH5L6S+7t7cU999yDF198MWznHgur1YpbbrkFe/bsgU6nizqGZVm88sorOHfuHLRaLaRSKd5//3383d/9HWj64vTuuusuXHfddVi+fDmamprwwgsv4NVXX8WFC9GDTbt27YLZbA69envn5hE70/zjlXUQ0BcFwBRiAb60vjKle50euBhUNju9GLa40jLHucKrR/oxanXnehoZ5UDH7E91nWsklSLa0tKCkZERrF69OnTN7/dj3759eOqpp+B2u8EwF31+Fy5cQFdXF2644YbQtUAgEHywQIC2tjbU1dVhzZo1aG1thdlshsfjQWFhITZs2IC1a9fGnMuGDRsAAOfPn0ddXV3E+yKRCCKRKJmPR4iCXi3B9tXl+N3hoBHdvrocclHymcX/9f55PPbXNnxxTTkWFMnx0qEe9Bmd+MySYvzD+gpcsbAQDD1/1SY5jsOejzpyPY2Ms6hYkespEKaR1F/z5s2bceLEibBrt99+O+rr6/Hggw+GGQAg6OqZPv6hhx6C1WrFE088EeGiUalUAILB4sOHD+P73/9+zLm0trYCAEpLSROLTLO2WhMyAk0bwk8B50dseP/sCGQiAdbXaLGgSB56z+nx47/eP4+XW3oxbAnucF9u6Qv7+rdODeGtU0PQyoS4tK4Ay8tUWFSswMJiOcrUknkjQ9w+YsOF0blfmf3c/k5sqNGiXDN/frb5TlJGQKFQoKGhIeyaTCZDQUFB6Pqtt96KsrIy7N69G2KxOGK8Wq0GgLDrL7/8MgoLC1FZWYkTJ07gnnvuwbZt23DttdcCCJ4oXnrpJXz2s59FQUEBjh8/jvvuuw9XXHEF7xRVQvIMmV344Z/P4I/HgvrwSrEAb58Zxgdto1hTrYHV5cPdLx2B1eULfU11gRQrK9QoVonxp2ODvFsdGuwe/On4YFh/3IYyJR69uRENZar0frA85KP2sVxPISucHrRg04/fx2eWFuO7W5eiskCa6ynNe9JeMdzT0xPmy+fD4OAg7r//fgwPD6O0tBS33norvvvd74beFwqFeOedd/D444/DbrejoqIC27dvx0MPPZTu6RMAeP0B/OrjLjz+zjnYPRczVSwuH378Vlvcr+0ad6BrPD3poyf7Lbjxqf24tE6H1ZVq3Ly6HNU6WVrunW98fH5+GIFJ3j49jHfPDONfrl2MHZfXQMyS1NFcQXEcNy9ytiwWC1QqFcxmM6kviMPbp4fxgzdPoztNC3k6oShg6/JS3HZpNdZVz50UVZfXj9XffxsOz9xMDU0Ey1D41jUL8c+bF+Z6KrOeVNY5oh1ECPHbQz3Y9cqJxANzBMch5DK6d8tCXLGocE70sX31aP+8NQBAUFLiZ++cQ5FChC+sKSfpx1mGnATmMBzH4XifGcf7zRAxNCq0UlRoJegZd+Bvp4cxYnWBoigwFIXucTuO9c0+zffGchW+cWUdrltWMiuziwIBDtc+vg/nZ0mnsEyjlrL4wz9dirpCeeLBhAjISYCAfpMTf2jpw5lBC070m9Fn5BeYna0c7zPjmy8egYRl8G83LE25hiFXfNg+SgzAFEwOL3rGHcQIZBFiBLKAy+uH2xeASsLO+F52tw+fdozD5PDiM8uKoRRfvGdLtwF3vtACg90z4+fMNpxeP77z2klUFciwsa4g19PhzbMfdeZ6CnlHx5gdV+d6EvMIYgQyQNeYHZ3jdhzpNuKDtlGcHDCDpWn8/bpy/GDb8pTu6fT48crRPvz4rTaYnV4AgOKPAtx+WQ3+rqEEfzo+gD0fdcLjC6Tzo8wq/AEOO186ggVFcqglLBrLVbi+oQQLivKzQOnMoAX751lWEB9+/NZZ1BXKcNXiolxPZV5AYgJpxOTw4Kdvn8MLB7pjjnnpzg24tC66hMZ0zgxa8MyHF3B60ILzIzYQ7a3kETI0rm8owedXleHyhTqweRR0/PbLxyKK52YCRQFfWleBL62rhF4tActQGDC58PH5MfzPp93omWXKrw9eX49/uipSDYAQGxITyDH/29IX1wAAwB2/Pox/v2EZblihh0QYPTfa5fXj8XfaseejDqK6OEM8/gDeODaAN44NQCNl8fiXVuHKRYW5nhZGrW683jqQtvstL1PhB9sasKJCHXZdLRViqV6JzzaWYvsvPsHQLNJrcnh8iQcRZkz+bItmMf4Ah9db+/ELHp2THB4//vUPx7Huh+/gv94/D5//ovsmEOCwv30MV//nB3j6wwvEAKQZo8OL//vKiZw3NrG5ffje6yfh8c/cdacUC/D9bQ14bedlEQZgKmVqCV755qVoLJ891ddErjw7EHfQDBm1unHf71pT9u2qJCxqC2UYNrtgdHjhCwTg9c+LH0nOeP72dbg6R/7mj9pH8X/+cIK3nEY8bl5Vhv+7dQl0cv5CiR5fALteOYE/HEmfGyoTrK5U4w//dOmsrwHJNsQdlGXeOjmIh147hTFb6vK/ZqcXR3tM6ZsUISG/b+7NuhGwurz4jz+fxW8P9cz4XmVqCR7dvhybFibv1hIKaPzbjUvx4bkRjNnyM4vsS+sq8NDnlhIDkCWIEUiBcZsb33n1JN46NZTrqRBS4O3Tw/jw3GjWYgOnByy484XDM9790xTwtUtr8C/XLoIsBTnvSZRiFttXl+OZffknXa1XifHDzy+flYV/sxViBFKguctADMAsxhfgcNtzh7CgSI6NtQW4bEEB5CIWGhmLukJ5WsXMmrsM+PqvmsOUVlNhdaUa39/WgGX69Pj0b1ypz0sj8PfrKogByDLECKSAyzt/c/HnEudHbDg/YsP/fHoxo0sooPGFNeW4/dJqLJxhA5R3zwxj50tHZvT7IhTQ+O7nlqJpfSXoNC6OS0qUUEnYUM1JPqAUC/APUdqZEjILyQ5KgZo5KmdMCAZOXzrYg8/8bB8+/4uP8eLB7oQLpXciyycQ4HB+xIpPLgSTBI70GGdkAMrUErz8jxtxyyVVaTUAAEDTFC5fwK9eJRusrFDjT9/ahFKVJNdTmXeQk0AKvHEsffndhPzlaI8JR3tMeOSPp3F9Qwn+6ao6LCxS4K+nhvDWySEUKkRgaAovHeyBQiyA3e2DxeWDUEBjQaEcFlfyu+wanQwFMiGuri/C7ZdVQyrM3J/o5Qt1ePPEYOKBGebrl9Xgoa1L0m7oCPwgRiAFJKQBxrzC7Qvg9dYBvN46ACFDR83vt7kv+vw9vgBOD1qSfs7nGkvx+D+szJqU8qaFuT0JKEQC/MfNy3HDCn1O5zHfIUYgBSq1pCXefCUdBV7TYWgK/7CuAv9+w7KsaumXa6RYWCRHe5ZVTBvLVfjy+krcsEIP+QyynAjpgfwEUqBjbO43BCdkltpCGdZXa9FYrsaWpUUoUohzMo/bLq3GQ6+dzMqzNFIWT391DTbUzh6V1/kAMQIp8O6Z4VxPgZCH6ORCqCRsRJETx3FQilnIRAIsKJLj86vK0FiuyotiqM+vKsOP3jo74xTWRCjEAvzPjg1oKJs9shXzBWIEkqRn3JH14zNhdlBVIENLtzHqe0IBjbpCOR67sjavMmBkIgG+sqESz3yYuZoBuUiAX399PTEAeQoxAknyDjkFEGJgdsaWYfD4AjgzaMEtzx7C/35jI9RSYRZnFp/7tiyCTibCyQEzBs0u2Fw+DJqdMDpmXkMgFTJ4/vZ1WF2pScNMCZmAGIEk+eNxkh5KiE4/j1ae50ds+NFbZ7H75sYszIgfYpbBnVfUhl0LBDicHDBj95/P4kDHeEr3ZWgK/++WtVhXTdRA8xlSLMYTjuPwk7+1EbE3QlRKVGI4eRaGHbgwDpc3t3LWiaBpCo3larx4xwb8omk1Ni3UQSvjf3phaAo/+eIKXJ7jNFRCYoiUNA8CAQ4PvX4SLx2cuQIkYW6yolyFY31m3uOXl6mw++bls8pPznEcRqxuXBixYdTmhkhAY02VFh+eG8WjfzkTUiUVMjR+0bQaW5YW53jG849U1jliBHiwv30MX332YIZmRpgLbKjR4mCnIamvKVaK8Lf7roRKwmZoVtnD4vKitccEm9uHGp0MS0oz08KVEJ9U1jniDuJB1zipCyDEhqaQUsbYsMWN//vqCXh8s1+QUClmccWiQnx2eSkxALMMYgR4cO3SYiJvS4jJmioNDPbUGrS8eXwQfzmZe/0ewvyFGAEeFCnFWFtFUtwIkWikLM6koBM0lafeO48+owN/aMnvlo+EuQkxAjzZWEdK3QmR1BXKYXPPLNOnfcSGrT/fj8PdycUUCIR0QIwATz67vDTXUyDkGTU6KQ7HqBBOFrPTi0NJBpYJhHRAjABPFhUr8L3PLc31NAh5hEKU3qyeC6N29Bocab0ngZAIYgSS4OuX1+DhG5flehqEPIBlKJwa4F8XwJe/kt7VhCxDjECS3HZpNbYsIUUw8x2tTAh/Bips8qHTF2F+QYxAknh8AVwYJSqi8x1TGsTVonG0x4TzI9aM3JtAiAYxAknyypE+dJKmMvMety+QlJZOMvz+MEkVJWSPGRmBRx99FBRF4d577+U1fu/evaAoCtu2bQu7Pjw8jK997WvQ6/WQSqW4/vrr0d7eHjbG5XJh586dKCgogFwux/bt2zE8nH1ZZ51cBGEWWwAS8pcqbWb6AhC5ckI2SXk1a25uxjPPPIPGRn6SuF1dXXjggQewadOmsOscx2Hbtm3o6OjA66+/jqNHj6KqqgpbtmyB3X5xx33ffffhj3/8I15++WV8+OGHGBgYwM0335zq9FNmy9JivPfAlfjKhkqsr9FieZkKOrko6/Mg5J5M9QPuGLVj1OrOyL0JhOmk1E/AZrOhqakJe/bswQ9+8IOE4/1+P5qamvDwww/jo48+gslkCr3X3t6OTz/9FCdPnsSyZcHMm1/+8pcoKSnBb3/7W9xxxx0wm8149tln8dJLL+Gaa64BADz//PNYsmQJPv30U1xyySWpfIyUKddI8R+fXx76N8dxONJjxJ+OD+L5j7uyOhdC7sjkQn2o04CtjaQ2hZB5UtrK7Ny5E1u3bsWWLVt4jX/kkUdQVFSEHTt2RLzndgf/kMTii422aZqGSCTC/v37AQAtLS3wer1hz6uvr0dlZSUOHDgQ9ZlutxsWiyXslSkoisKaKi2+97ml+NY1C5AHrWMJWaBr3AGxIDOngbdPk1RRQnZI+jd47969OHLkCHbv3s1r/P79+/Hss89iz549Ud+fXMx37doFo9EIj8eDH/3oR+jr68PgYDBdbmhoCEKhEGq1Ouxri4uLMTQU/Y9l9+7dUKlUoVdFRQX/D5kiFEXhX65djMZZpBFPSJ1KrRSuDCmA/vnkEIwpitIRCMmQlBHo7e3FPffcgxdffDFs5x4Lq9WKW265BXv27IFOF73DEMuyeOWVV3Du3DlotVpIpVK8//77+Lu/+zvQdOq7rF27dsFsNodevb29Kd8rWa6pJ3UE84EegyNjwoIeXwC/bSZNjAiZJ6mYQEtLC0ZGRrB69erQNb/fj3379uGpp56C2+0GwzCh9y5cuICuri7ccMMNoWuBQHDnJBAI0NbWhrq6OqxZswatra0wm83weDwoLCzEhg0bsHbtWgBASUkJPB4PTCZT2GlgeHgYJSUlUecqEokgEuUmYFtbKMvJcwnZZ8jiyti9f/1JF+64vBbCDLmcCAQgyZPA5s2bceLECbS2toZea9euRVNTE1pbW8MMABB09Uwff+ONN+Lqq69Ga2trhItGpVKhsLAQ7e3tOHz4MG666SYAwJo1a8CyLN59993Q2La2NvT09GDjxo2pfvaMoZwDnaII/OgzOqGRZubnPWxx48+kgpiQYZI6CSgUCjQ0NIRdk8lkKCgoCF2/9dZbUVZWht27d0MsFkeMn9zJT73+8ssvo7CwEJWVlThx4gTuuecebNu2Dddeey2AoHHYsWMH7r//fmi1WiiVSnzrW9/Cxo0bs54ZxIeVFWpIWAbOPG8mTkgPVQUyGB2mjNz72f2duGmlHhTJNiBkiJRSROPR09OTtC9/cHAQ999/P4aHh1FaWopbb70V3/3ud8PG/OxnPwNN09i+fTvcbjeuu+46/OIXv0jn1NOGSsLi7msW4LG/tuV6KoQskMniwRP9ZgyYXShTZ6YwjUAgjeYzBMdxuGdvK944NpDxZxFyS61Oho4MSonsf/BqlGukGbs/Ye5AGs3nERRF4VvXLMj1NAhZoHPcDrmQSTwwBUQCGiXKxJl4BEKqECOQQRYWK3DZAtKWcq7DcUBNhjLC3L4APjw3mpF7EwgAMQIZ58pFhbmeAiELSIRpD6+F+Pl752F1ZUa6mkAgRiDDSDO4OBDyB5Mjc9W9x3pN+NL/+xSBwLwI3xGyDDECGaZpQyWaNlTmehqEDNMxas+YjhAAnBqw4MVDpIKYkH6IEcgwFEXh4RuXYUlp5jOSCLnDF+CwVJ/Zn/GvP+nK6P0J8xNiBLKAgKFJg/p5gCvDxYEsaWZEyADktypLrK/RZkxsjJAfnB60okyduXTOjlEbvP7MqJYS5i/ECGSRS+tIuuhcpyyDRV1uXwCnBjLXF4MwPyFGIIt8cW3mexoQckv7sBWZFP18+oMLmbs5YV5CjEAWqdBKiQbMHMfo8GJlRebcfm+dGsJz+zszdn/C/IMYgSxz00p9rqdAyDBtQ1ZUaDNn7B/502m83zaSsfsT5hfECGSZIkVuGt0QsofV7YM/w4Vdj799LqP3J8wfiBHIMjIRqSCeD2Ta7Xesz4z2YWtGn0GYHxAjkGVWVKhzPQVChqnVyXC4y5jx53zt+Wb8+pMuIidBmBHECGSZukI5FOQ0MGeRCBn4AxyysSz3m5z4tzdOETkJwowgRiDLMDSF+z6zKNfTIGQAigIWFsnRbXBk9blPvtue8WplwtyFGIEc8PXLa7Dz6rpcT4OQZtZXa3G8z5z1545Y3dj1yomsP5cwNyBGIEd8+7p6bFlSlOtpENLEmioNDnYacvZ8jVSYs2cTZjfECOSQf968EDSV61kQZkKNToo1lRoc7cl8IDgWaimLezYvzNnzCbMbYgRySGO5Gt/ZujTX0yAkCUUBjeUqLC1VonPMgZYeI3KVoENRwKM3N0IlZXMzAcKsh6Sp5JhLarW5ngKBJ1oZi7pCOfpNzpz4/qPxyI3LcH1DSa6nQZjFECOQY+pLlChSiDBided6KoQYVGgl0EqFONZnhsGeO7fPVGgK+NH2RiJKSJgxxB2UYxiawiM3NUAmZHI9FcI0dHIh1lZp0Gdw4lie7PyBoAF48suriQEgpAViBPKA6xtK8ORXVuV6GoQJJCyDDTVaWF1eHO42ZqXwKxn+YV0ltjaW5noahDkCMQJ5wjX1xbh1Y1Wup0FAMOh7sNMAty/flv/gyfGKhbpcT4MwhyBGII/47ueWorZQlutpzGtEAhpnhvK3e5c/wOGfXjyC/znQBY7LPyNFmH2QwHCeMUoCxDlleZkKh7vzI/gbj+++fgr/29KH+69dDJam0NpnQseoHWKWxh2X16JaRzYTBH4QI5BHnBm0wOry5Xoa8xKpkIFOLsKQxZXrqfDmWJ8Ztz13KOK6gKbx7zcuy8GMCLMR4g7KI9y+QK6nMC9ZWaGCw+NHj8GBPqMz19OZMd3j9lxPgTCLIEYgj1hRrkYh6TyWVViGwrBlbrngGsvVuZ4CYRZBjEAeIRTQ+PplNbmexrxiVaUGg+bZ4wLiQ0u3EQc7xkngmMALYgTyjG9cWYsvrydFQNlAIRbgzGD+ZgKlyv7zY9jx68O4//fH4PMTFyMhPsQI5BkUReG7n1sKAZEXzThLSpRzLhDPMhQ21GgRCATw6tF+fNQ+luspEfIcYgTykHfOjMBH+sZmlDK1BC3dudP/zwRSIYMFRXIc7DTA4Q2eAF5u6c3xrAj5zoyMwKOPPgqKonDvvffyGr93715QFIVt27aFXbfZbLj77rtRXl4OiUSCpUuX4umnnw4bc9VVV4GiqLDXN77xjZlMP2/54OxIrqcw5ymQC+GfQ3Z2QZEchXIhzgxaw66/fXoYQ3Ms5kFILynXCTQ3N+OZZ55BY2Mjr/FdXV144IEHsGnTpoj37r//frz33nv4zW9+g+rqavztb3/DN7/5Tej1etx4442hcXfeeSceeeSR0L+lUmmq089bXm/txytH+3M9jTnN0lJl3khBz5RKrRQqiQAn+qPHNrx+Ds/u7yB9KwgxSekkYLPZ0NTUhD179kCj0SQc7/f70dTUhIcffhi1tbUR73/yySe47bbbcNVVV6G6uhp33XUXVqxYgUOHwgthpFIpSkpKQi+lUpnK9POa14gByDgOz+yPA6gkLNZVa9BndMQ0AJO8eLAHJocnSzMjzDZSMgI7d+7E1q1bsWXLFl7jH3nkERQVFWHHjh1R37/00kvxxhtvoL+/HxzH4f3338e5c+dw7bXXho178cUXodPp0NDQgF27dsHhcMR8ptvthsViCXvlOxzHzZkdar6yqkKN3llaECYU0FhRrsKaKg38/gCau/h1NHN4/HjhQHfmJ0iYlSTtDtq7dy+OHDmC5uZmXuP379+PZ599Fq2trTHHPPnkk7jrrrtQXl4OgUAAmqaxZ88eXHHFFaExX/nKV1BVVQW9Xo/jx4/jwQcfRFtbG1555ZWo99y9ezcefvjhpD5brvEHOFAkKSijWF1e6GRCVGils0IjSCkWYEGRHBwHnBu2ptzX4K+nhvDPmxfiwqgN75wexudW6FGmlqR5toTZSFJGoLe3F/fccw/efvttiMXihOOtVituueUW7NmzBzpdbPnbJ598Ep9++ineeOMNVFVVYd++fdi5cyf0en3otHHXXXeFxi9fvhylpaXYvHkzLly4gLq6uoh77tq1C/fff3/o3xaLBRUV+Z1/L2Bo3LNlEb772slcT2VOsrRUgdMTgdNhqxvrqjVo6c5df+BErK/RoqXLgCM9phnf6+yQFX1GB+584TA6Ru14+sMLePqra7ChtmDmE51l9Bkd2HduDGopC7WUhUYqhErCQisTQszOv+ZOFJdEWeFrr72Gz3/+82CYi98ov98PiqJA0zTcbnfYe62trVi1alXYtUAgmLpG0zTa2tqg1+uhUqnw6quvYuvWraFxd9xxB/r6+vDWW29FnYvdbodcLsdbb72F6667LuHcLRYLVCoVzGZzXscSvP4AbnvuED65MJ7rqcw5lumVODUQ7hZsLFehbciaN7pNUiGDUpUYBTIRDnWlN4V1XbUGzV0XTz8KkQB3bKpFtU6KxSUK1Jdk9u/C5w/gwqgddYUyCJjsZ6dzHIffNffiB2+egc0dGRdiGQqb64uxfU05tiwpQoADOsdssLh88Pk5SIUMGspUWZ93MqSyziV1Eti8eTNOnDgRdu32229HfX09HnzwwbDFHgDq6+sjxj/00EOwWq144oknUFFRAZfLBa/XC5oO/6VgGCZkMKIx6V4qLZ1bHZZYhsZLd16CtiErTg2YcbLfgj8eHyAS0zOkRieLMAAAcLzPjIXFcvgDHDpGcyu8tqRUgVGrGxdG7biQgblMP/FY3T787J1zoX/ftrEKD9/UkLbnjVrd+MORvolnc/jVx10YsbrxwLWLcPc1C9P2nHi4vH789dQQTA4v3j07gn3nRmOO9fo5vHVqCG+dGsKGGi1ODVjCjMUX15TjsS+uyMa0s0pSRkChUKChIfyXRCaToaCgIHT91ltvRVlZGXbv3g2xWBwxXq1WA0DoulAoxJVXXolvf/vbkEgkqKqqwocffogXXngBP/3pTwEAFy5cwEsvvYTPfvazKCgowPHjx3Hffffhiiuu4J2iOttYXKLA4hIFbl4NfGfrEnzaMY43Wgfw55ODc67KNRsY7B5sqNGia8yO4WkGtX3YBgDQSFnU6GSgKQrtIzaYnd6szW9BkRznh23wZtA35U0gIfHrA91YWanG51eVp3T/j8+P4beHeqCSsLi0Tocn32vH2SFrxLifvdMOjgNuWlmGyoLMpHm7vH78rrkXv/zgQkry4Ac7I09hc9V1lvZ+Aj09PRG7+kTs3bsXu3btQlNTEwwGA6qqqvDDH/4wVAwmFArxzjvv4PHHH4fdbkdFRQW2b9+Ohx56KN3Tz0sYmsJlC3S4bIEOj2xbhg/aRvFG6wDeOTOcN26MfMfs9OJgpwEUFWwcQ1HAiT4zVldpMGByYNDshtHhhXHC/16ulkAkoDGShROYUEDD5fFn1AAA4JV08H/+cAJmhxdqqRD9JieUYgEWFSsgEwkgFNAQ0BRYhoZayuIvJ4bwytE+KMQszE4vDk1ZOF882BPzGf4Ah5+8fQ4/efscnv7qalzfkN7T/F9PDeF7r59Muzrsygp1Wu+XLyQVE5jNzJaYQDJYXV78oaUP//7H07meyqykQCaE0eHBumpt1J2fSiJAfYkSbl8AF0ZssEbxI6eDDTXRn59u1lRq0NKTnowomop0L6WChGXw7G1rcemC9PRNPtZrwhefOQBPBjZH7/3LlagtlKf9vukklXWOaAfNYhRiFkXKxFlahOiM2z0IcIjp9jE7fTjYaUBrrwkunx/razRpT+GtK5SF7aAzSTrnnq5Di9Prx63PHcLj75yDy+uf0b1O9ptx5wuHM2IAgOBc5yLECMxySIXxzBkwJS4e8/o5HOo0olYnwzJ9ek6SApqCP8AhW0dxf57mwvoCHB5/px0/e/tc4sHRvt4fwO+be/GFpz/JqPvO5Z2brlfSY3gWc3bIgr+dHs71NGY9GpkQFp7B9smsnSqtBIUKMVp7TajUSqGTixDgOHj8Abi8fjg8flhdvrBThlBAQyESYNwelHBYU6XJihsICJ4Ceo2xK+zzgZYUivf2t4/hoddOoGs8859NJWEz/oxcQIzALCZbboS5TK1OBkMKujrdBie6DU6wNIWOMTs6xqKndNJUcPFgGRpGuwd6tRjjdg8qtdKsSlmvqlCnpegskxzuNuL3h3vx92v5FXX++cQg7tl7FN4sycHO1davxB00i5kuG0xIHq8/AJMj9VTQRBk9AQ4wOrwYsbrhDXA40W/BhhotRAIa2UrskosE6M7CTjkd7HrlBK/Nze+be3H3S0eyZgAA4O6XjqB7PLe1JJmAnARmMWeH8l8UL5/Rq8Q5EZPjOKB9xJa159WXKGaFThIQjFvc/dIR7LymDp+cH4fD48cNjXrUFcnh8vohoCm8c2YYez7qzPrcPmofw4VRG6oKZFl/diYhRmAWs6RUiaN5fsTPZ8o1UgxkueHK8jIljvZmb0Fu0CtnjQGYZMTqxh+PDeLwhMRFPrXI7DfNvQY9xB00i/nu1qVYWJTfecv5TLb7Cqyt0uDUgCVrLgydXIiBWbpoefO0CPLkHJR6J0ZgFiMRMnjsiyuI/HQKSFgGbVEkDTJFhUaCo72mrCmWKsQCyEWClILe+UCf0Yl8/LX+3eFe/OKD85hLNbbECMxyVlaocdvG6lxPY9axpFSRcZmGqRQrxVnL05cIGZSoxFlJm8wU4/ZgJXc+8uO32nDHrw/jZP/cOBUQIzAH+PZ1i7G4WJHracwqHJ7sVn9mSnJiOiIBjeoCaUgUbzaTz6eYd8+O4HNP7sdN//UxXj3aN6tPBsQIzAFkIgGe/MqqXE9j1qBXiaOqW2YSpTjzORgsQ2FBkXzOpA4H8rTCeSrHek2473fHsO2/PsZbJ4dyPZ2UIEZgjlCjm1tpa5mkXJsZ+eJ4dI05oBBlzhCwDIX6EkXUngmzlT6TE2rp7KjSPdZnxjd+04KfvX1uVhivqRAjMEdgGXrOlrWnE5oCLmQxR3+SUZsbi0sz47IT0BSWlCpxon/uGAC5SIBVFWoIc9CBbCY88W47/nh8INfTSIrZ9R0mxGVtlSbXU8h7GvSqkHZPtjnRZwKdgZSXlRVqHJ9DqYsiAY36EjkOdhqy0s9hvkOMwBxiY93c7HyULoJSDbnLP3f7uLTrzywvU826YrB4LC5WoEAuRK8h+5Xc6eLTjtml6UWMwByieo6Vs6ebpXoluscd2FCjhVCQ/V/9xSUKFMjSawT8OTRq6WJhkRwbarSoK5ShbdiKAZMLbA5+Puni/MjsCswT2Yg5hG6Oqhymg/U12pAw2cFOA3RyIWoL5VlRYl1epoLB7kHbkBXra9KX+y4RMlnPckoXIgGNxnIVeg2OqDpKs7kAMpuidulg9ppbQgRzYVeYCYoUoojFfszmwaFOAzbUaCHIhKMewcb162u0ONFvRv9E45ohszNtC1yFRpK1CuR0QlNBUbvmLiOGYvQBnsVp9xi1umdV3QAxAnOIUWv+Ftfkkso4KaEHOw1YXaXG2ipNWlxENAWsqFChsVwFy7Tm6wDQY3CmrRJWnsGU00yytkqDYwkC2fmqHcSHfpMT23/5Cc4Mzo5srdn5W0SIylsnB3M9hbxjUbEcR2I0VxfQFNZUadDcZUCAA5QSAVZWqNFndMDp8cMf4EI7baGAhpChIRTQEAlonB+1RexW5SIBSlRiHOuNv8Ad6jRgbbUG54asvDuaRZ//7NzD8VHi9PpnrxEAgCM9Jtz41H7cu2URvnlVHag89m8RIzBHcHn9eOfMSK6nkXcEpizk06kqkIa1d7Q4fbFjBNO8FnWFslCrSSB42mBpClIhw2teh7uMkAkZbKjR4ni/Gc5UZCzyd12JyaJiOc7xkLSYPc6U2Hj9HJ54tx13bKqBSMDv9yIXECMwR3jlSD9sWdKnmS0sKJLjfIzCMJpC2CKeLCxDg2UoeP0clumV6B6zw+bxg0KwdzCffrl2jx8HOw3QSFk06IO9IXxxnPwKkQAqKQuhgIZgwuA0lqvA0BQoBBuyODx+9JmcqRmVLMB3MZwLRgAIxj7y2QAAxAjMCY70GPGzd87lehp5x4jFBa1UGFWIrFIrnZHK5tkhKxrLVfD6AmFSDRyCDdNXVqjR2mvidS+jw4vmLiNKlCJUFcjQZ3SGAsnlGgn0agkGTE70GZ1hQnQSIROzSKxCI0GRUgyKAsZtHnSP23MeRJaLBBi28OtvwOSx+yQZRixu+PwBCPK48jl/Z0bgzU/+1oZRUlkZgcXlQwAcGstVEe+lo2jreJ8Z0hjBWXsKp7IhixsHOw3oNzlx5SIdlumV6DM6cajTgL4obTDt7ti7/V6jEy3dRhzrNaFIIYJMyKC+RIENNVosLVVCzGb/T39JqYJ3BTDLzA0jMGRx4bfNvbmeRlzISWAO0J+DPrmzBZPDC5PDjOVl4do66eoqZnVFb1LfPmKDUixIOfBrcngTisEN8WiNuaJcHYp7TK0pYKigf14tFcLp8eH8iB1Ob+ZcSDSFpJrdz9agdzR++rc2fHFNOcRsfrqF5s53ep7i8wdQqBChvmR+9RNYXqbCMr0SFVpJ3HESlsGqClWYAVhTqcGpgZkXWamlLNRSYcz36wpTb/05mGCBL5AJE8aA1lVrYkpK+Dng3LAN/UYnOkbt8Pj8WFQsx/oaLZbplRCluWJ3RYU6KR0gag6tTEaHF/vzqE/ydMhJYJbTY3CgeaIhd5lajHKNFB1j9jnvHnJ6/Tg/YsPSCWVOhqZAU8Eio8ngarFSBKlQgKNTUjaXlirQEiNlNBnW12hxtMcYt+JYkKJLo1gpwnCMIqpJipSiuEJ4i4rlOJIgOC0UBIPb9okg8tSsHQENLNMrMWBywuiIftrhA00FBe7OJpkzb3J4sa5aA2pKChRFARw4UKDA4WJy1GSog5r4/8kgeb/JmdCYZosDHePYsrQ419OICjECs5ypGS79Jhf6TS5QABr0SggYGqcGzLOujJ0PXWPBBWvE6ka5WgJfwI8hS3BRlAkZLNOr0DZsiVhM5eL0yG33jNsTfl8HU2zyrldJEhoBqTD2n65CLIDR7kWiH/uKclVoAzEdXwA4NWBBuVoChqYwZku+EFGvEiPAcTjSY0r6a60uX8y58aFYKYLXF8D6idNQroPixjzukjaHDl3zk3PDkW4NDsDJAQtae02QCBmsr9aiRpf9RiqZQi4SYLKgdMzmQZ/JCZXkYqDX7vHjUJcBZmeku4SPH50PfPy7fSYnilIIQLM8MkniKV0sLVVi1BbfiKyuVPNaZPtMTghoCiUqccKx09EpRDFlITJNpVYKg8OLQ11GrMkDiXXbDIoCMw0xArOctVUaKOK0LrQ4fTjUZUDnmAO1OhnWVWsy2uEqG0Rr1cjX9dJjcKA4DZlBOjm/e8STrIiF2ZnY/RKIo03jShDgVYoFaEtCeG7I4obfz6FcEz/+MolcJMDqytz2OJhMsQWA5i4j1ue4aX2+uKWiMbtXAwLWVGlQqBDBymOn0TFmR8eYHSxDYVWlGm5vAKezqG+iV4lRqpYgwHHguOBC5g9cfPkCHEwOT0IftFwsAKatL+4ktGaqdTIMzzBmEm8RjjauRCWGP8AljNWwDIWOscQVtfGyjhJpIC0pVYZVSvNh1OaGRsqiRidD51j0IjuKAhrLVBgwuVJyAaULrUyIgWmuuMPdBiwpVeSs/3KsLLJ8gBiBWc4bxwbQkWTlq9fP4ejEH2mxQoQqnQzd4/aEfuhUYBkKS0qUYGgKR3tNGOCxIxIyFIqVYpSqxfD6OZwbsoaClwCiZuSYJwzH2moNOkbtMNg9oKmgZLFQQEMqZFCoEEPI0OgxOLC2KnbmDB+m7jTj0TVmD8lYUwAWFssxbnWDZWiopUIYHR6UqsRweQOQiwWQsDT2nx9PeN/OURvELA2XN3mNnXYesg3RMDq88PoDWFgkjyr/vKREkVAYLhvIRQIYpgXNAxy/E1amSOXnlC2IEZjl/G6GhSjDVndoVzyZGnhywALPDFQcKSp4LyFD48ygBcf7k1sYPH4OvUYneo1OFMpFWKZX4VBXcOcaq4ho1OYOdtma4ucOcIDTG4DTG4DZ6cOgOfg5KQRdIpfUaDFm92DU6obL64dEyKBYKYbPH0goKTFscaNAJkzYqlKvkaBnPHgvDuEL8OT3fWrqJF+3hS8ANJQpo1YlT18Ap7K0VDmj05/N7Uef0RFVkuPskBVqKQvTDLKJ0kGszz9gckErE8b9/mQKty8/ZTyAGcYEHn30UVAUhXvvvZfX+L1794KiKGzbti3sus1mw913343y8nJIJBIsXboUTz/9dNgYl8uFnTt3oqCgAHK5HNu3b8fw8PBMpj/rMTu9aW0teGrAgiM9JggZCuuqNagrTL5T2dpqDYoVIpzsD97LOcMdULVOikNdQX0drUwIMcvETMvkqzzJAWgbtuHTTgPOj9hgdnrh9gVgcnhhdXpDcYMNNVosLI6d6x+v6pihKSzTK9E1ak+YpTMVTxLqmRanN2pvgh6DA7E8QnzdWPFwegMYsbpQMS1GEOCARcUKLC9TQScX5qzq1+b2RQ3IU8idW8bh8edtj4GUTwLNzc145pln0NjYyGt8V1cXHnjgAWzatCnivfvvvx/vvfcefvOb36C6uhp/+9vf8M1vfhN6vR433ngjAOC+++7Dm2++iZdffhkqlQp33303br75Znz88cepfoRZT8+4A/4M5L7Z3P5Q5kh1gRRFCjHahq1xj9MNZUr4/FzYTjwduCeMCJ9cdWMadngDZlfIfTO5Uy9SiFBdIIXJ6Q3LpZdNKIbq1WKUayTw+DjY3T6YHF6M2tyhil+NLHZB2XT6jPyrajvG7FHdWl4/F6FyCgRPZ4mqkPlicfogETARO+u2ofDfE7GAhlQkgIRlIGbpkPCegKHBUBRoigIowOPz4+yQNW1uk0KFKOyERSGoGjsTvaiZ4PYFcLzPjBUV6pw8Px4pGQGbzYampibs2bMHP/jBDxKO9/v9aGpqwsMPP4yPPvoIJpMp7P1PPvkEt912G6666ioAwF133YVnnnkGhw4dwo033giz2Yxnn30WL730Eq655hoAwPPPP48lS5bg008/xSWXXJLKx5j1ZLLMf5KucQe6xh1gaQqrKtTw+gMYsbqhkQkhEzKgaQo94w6c7M9MgPncsDWk1pmIZCpS43G4y4AFhTKcn1hER6zu0L2DBkEGg8MDAUODpgCfn8OhztjGz+r2YXmZCicSuMUK5aKEqZ3T6Ri1Qypk4JimGqqVCcOMwPpqLY70pLeV5rDVjQWFMlhd3tDPx+z0Qiyg4ZpwJ7p8Abh8/IyzfCKduWvcPuOf5VRJ7w01WrSP2HjHcTLFLc8exNX1RShWinH14iKsq9bkhbBcSjPYuXMntm7dii1btvAa/8gjj6CoqAg7duyI+v6ll16KN954A/39/eA4Du+//z7OnTuHa6+9FgDQ0tICr9cb9rz6+npUVlbiwIEDUe/pdrthsVjCXnONbBiBSbwBDp0Tvu1RqxttQ1Yc6THhcJcxbYtvNFy+YCCSD+k6EwW44CtaLv6I1Y1DXUE30rDFhSWlyoSf3+Tw4kS/Gcv0yrjjynimYE7F4PBgeVmkQN7UZgMbarQ41GVAMmEepVjAS2Tv/Kg9YndbpEy+pgAAbBP1HaNWN1ZUqLCiQgVJino7k01c1lVrcLDTAIPdk/OiSYvLh9dbB/D/9nXgy3s+xervv40dv2pOKl03EyR9Eti7dy+OHDmC5uZmXuP379+PZ599Fq2trTHHPPnkk7jrrrtQXl4OgUAAmqaxZ88eXHHFFQCAoaEhCIVCqNXqsK8rLi7G0NBQ1Hvu3r0bDz/8MK85zlaW6ZVYXanOWjqeyeFFrU6Wda13RZqqfJOhY8yODTXauKmUXePBLCO+mBweqCRsTLdaqu0tj3QbUaIUY2iKTLNpokJ1chHkg0IkwKISBdxeP84MWuAPcKjUSsDQNAQMBblQAFZAIxDggm4cBGUcjA4PNtRo4fD4wTJU2DxSgQNC3dkYClhQKINaKgRDUxdTijkOPj8Ht88Pty8Ap8cPh8d/cWPEcVhQJJtR1XGmsbh8ePfsCA52GvDX+65AmTr5TUA6SMoI9Pb24p577sHbb78NsTixtbdarbjllluwZ88e6HS6mOOefPJJfPrpp3jjjTdQVVWFffv2YefOndDr9bxPG9PZtWsX7r///tC/LRYLKioqUrpXvqKTi/DiHZfg7585EOZqoClgqV4Jh9uPjhg53alyZtCKUpUolGmTDXKRzQEAJ3lkNR3uNvLOuOk3ubC4WAGb2xc1lmOZYhxEAhoLiuTBuANFhRZeu8cLmYjFkNmFHkPQv+0NcChVXzQCBTIh5CIB1lUnrgqezP33+TmcHjSHNcOxe/ywG/i5UOwqH8Zs6d9t+zlMuOX4/R6XqSUoVYnQOWZHiSo3i2qy2Nw+jFrdOTMCFJdEyPq1117D5z//eTDMxSOa3+8HRVGgaRputzvsvdbWVqxatSrsWiAQPJPSNI22tjbo9XqoVCq8+uqr2Lp1a2jcHXfcgb6+Prz11lt47733sHnzZhiNxrDTQFVVFe69917cd999CedusVigUqlgNpuhVMY/ls82BkxOXPezfXB6/bhlYxW+dc1CaCeCkacHLPj2/x5LW0CwukAKrUyI04OWrOU+0xQgYpmcdMvSq8URhUfTKddIYHX5eOehRzthMFSwiEsmEsDs9OL8iDWh+6ZBr0SAC6bNTtZDnB60hoxmrU4WsQloLFdBQFMwO70YsbhgjdOTIFkSnZyyxdoqDY72mjKSNJEJKrQSvH3flWmRmk5lnUvqJLB582acOHEi7Nrtt9+O+vp6PPjgg2GLPRD0208f/9BDD8FqteKJJ55ARUUFXC4XvF4v6Gn64QzDhAzGmjVrwLIs3n33XWzfvh0A0NbWhp6eHmzcuDGZjzAn0asleKppNco1kgj54qV6JV7beRk+ah+F1RXcrZ3oM4GmKXAc8FH7GMamBSPjFSGppWzI/VSsEKFQKYaUpRFAUB9lyOJKe554gAPqdDKcTJMhS4Zo1afT6TM6sUyv5G0EWroNWFqqQI/BicUlCjBU0Lef7OebPn5ttSbs1KSVC0NGgKEpLNer0NpnSuoZydDaa0ShQpRTBdu6QhnaR2yzxgDQFPDozY057TWQlBFQKBRoaGgIuyaTyVBQUBC6fuutt6KsrAy7d++GWCyOGD+5k5+8LhQKceWVV+Lb3/42JBIJqqqq8OGHH+KFF17AT3/6UwCASqXCjh07cP/990Or1UKpVOJb3/oWNm7cOG8zg6Zz5aLCmO+xDI1r6qPL2Hp8AXzUPopxmwcilsaaKg1KlGJ80DaKl1t60dJtCjMS1JTE9KmFZlNRiAUoVYmhFLNgaAourx/jdg8GTM6U1RxlOdQ7WlqqRNuQJW6+/6kBS1h8Jl5GEytgIBcL4A8EQu6X6hQ0hqZzesASlpkzNXizslyFlgzHjty+oL5QroxAY7kKMiEzo97R2eb72xpw2YLYrvJskPa/rJ6enohdfSL27t2LXbt2oampCQaDAVVVVfjhD3+Ib3zjG6ExP/vZz0DTNLZv3w63243rrrsOv/jFL9I9/XmHUEBj85JIA7FlaXFI/3zE4sJ/7+/E/9vXgbNDVpSqxHEFsawuH6yuSFkBAR3MgCmQiiBiafgCHMxOLwZMzogUx+nkqs5mMvV17UTz+HjT8PoDkAkZVOtkGLW6UaIUY8DsjJBhXlqijEgplYhmvhN0ePxhTe67xx2QsAycXj/MWVKxPNpjQn2JIqyLWTZYW61BS1fw57OuWpPXAeFJrqkvwlfWV+Z6GsnFBGYzczkmkC1ePNiN77x6MmyhSRc6uTDYC3dix293+zBkcYfcG41lqqTlJ9LNZBFZPNZUqsN23AqxALWFslC2S6wG9OnK8lpcogilHK6r1sDk9ELCMjg7aIFnBkHbBUVyqCVsyAhyHIcAd/G/ITFAjoNOJsTBTkPWNPynxyIYClhQrMh56mUiXv3mpVhVmV6Z64zHBAjzm6YNVegYteP3GWicPWbzRG1cohAxKJ1obJJrLkQRTZvK8rJIl4vV5cOxXjPWVWtwrM8cU7YgXZ+vbciKco0EZocX3eMOjFjdqNRKoJIKU3LT0FRQqTaZnXU7gsVpk3pPmaK6QAoxS0cEo/0cMGh2Yn2NJm4RXy5RiAVYUa7O9TQAkH4ChCT5zmeXYGtjKcRp7kEbC6vbj3PDtpRbNaaTBQmK1uIV7zV3GdFYpozpr6ajiQClSJlagmqdLJRy2mNwggIS9mOejoRlsLRUmZJr5WivEbW65LWn+KCWslhbrUH3uANnh6IbZovTh0OdRqyp1OTFBmI6a6o0oPNkXsQIEJKCpin8x+eX46HPLeHdWCUd9Iw7ciZINsmZQQs21GhRGqXL1vIyZYSq5lQKZEL0xMm596fBKysVMlhbpYHHF8CJfvPFADGClc4mhzehIZvKklJFyhlZXj8Hg8OD+hJFSl8fDZmQwfoaLby+AA53xY/PTOILBPJSuC2bfzuJIO4gQtLQNIWvXlKNm1eX46FXT+KVo/0Zf+aw1Z3zPHSLyxd6fkOZEjRFhbpnxQtsswwFpUSAzrHY4mV+fwBaKQuFWACJUACJkIGADgqsTV3CKAT975N+eJ+fA8sE031PDZhDYnI1OmnE86wuH+QiH4QCOqFU+IoK1YxjFCaHF2aHNyRbkepaTFHAmkoNLozaEsZkprK0VIHTg5ac9xeORleaizhnAjEChJSRCgX4wtryrBgBADjVb44ru5BNJrOGChUiNOiVsLmDNRjR5rahtgCDCcTLnN4ADA4vDGmqsSiUi6MancEpKqmxkAoZDCaojeALB+BgpwFXLSrEsT4TLzXYqSwuVsDjDyQtmb6wSI7OcUfO9YJicbzfjBGLK2WdpXRCjABhRqyq0ODqxYV4v20048+yefxYV52ajzpTjFrd6ByzB5VWGQr1JQpIWBqsgEZzlxFilkFrtxE2jx+FchGqdVJQAHwBDh5/UPPG6vLB7k5vCme83goujw+X1mrRPREroGiAmYhJePwBWJ3etIoCVmgl2H9+FEqJMKn00VSz0KoLpBiyuHJSYc4Xjy+AW587hN/dtREqafa1saZCUkQJM+b8iBVbf74/qT6/qSIW0BAwNGxpXjRTJVbKJxBM0fQFLrbyjEe6TzhVWim6DeEnAY2URbVOhqM9JlRpJRgwuzK+U1ZJgs2AJvsSU5hItU3gHlpepsLJfnPSYoVlagkcHl/SJ45csbWxFP/1ldVpu18q6xwJDBNmzIIiBb52WXVWnuXyBRJKMmeTeFlLZwYsEPLUi7ekuePVgDnc/bS2KtwgdRucac9Rn4qEZbC+OpiZM7Ux/aR7aGGRHCsrVFHluusKZWgftiZtAIoUInj9gVljAADgYEfutZaIO4iQFvxZ9L0e6jRArxLzalqfaeKldto8ftjdiRekTPTl9fo5FClEKFNLYHP7ovrUmzsNUXsFzwSVhMXiEgXODFpwKI7bbrJDW5FChGqdDF1jwUYyBTIhjA5vWGYTH5QSAUQsjV6eqqe5QCZk8B83LwdDU3j/7Ch0ciH+fl3ulY2JESCkhdsurcZzH3dmJRODA6CUsHlhBDrH7FhSqsCZweh+bj5yDQqxYEZGQK8SQyJkQr2Sa3Uy0DQFq9OLozFcVUD6mvBMsqhYjj6DI6kMnsmubQI6WPkrZml8eG4sqeeKBTSKFWK0p9GYZYL/uHk5blpZBgD4XKM+x7O5CDEChLRQoZVifY0Wn2bheFtXKMupUuVURq1uMDQFmkJUAzhqSTxPmZCBXMhAJWUhF7EQs8G4B0NTmH7OmCrbAAC9BkeEMfQFOJzqM6OxPFrHsXDOj9ii9ilOBZWExbkU5cV9gaCbaFIWm298iaGCRXy5UJhNhrVVmpAByDeIESCkjRtXlGXMCLA0hboiGQQ0nXd/8ENmV1TtH77BXjErgM3jh83jBxD7dJNIuG+Syf66fKu6O0ZtIaG5mZCOqmevn0NdoZSXEqhCFBTrO5Gh/tbppGvcDovLC2UOuuQlghgBQtrYWFeQ9nvqVWKUqsRgaCqujznX9BqdYCiEyU3r5EJeRoBvJbRSzCY0AiIBFXIt8XX3GCYKuuweH0QMA6PTg+5xR9Ka/IFAsHBNzDIQCegIo8AheILhuCkFbwEOPo6Dzx8AxwX7N5SpJaF2ktS0rw1wwd3/ZPMdh8ePBUXyi20nAxwC3ET7Swrw+QPw+AJw+wJwef05Kxwbs3nw5Lvt+M7WpbmZQByIESCkjVKVGDIhA3sa8rPlIgHqSxRo6TaG3B1LS4NFWT2G2JW3uWLU6o7Ia+fbG5nvDloijC83XaIUQSlhQ0FXPlkyFAWsrtBgyOyEzR3s+wAEjcnCIgWUEhZeXwAjNjecHh80UiE0UiFAAWaHF2anFy6fHx5vAM0Tn93r92EyQpKMOuqaSg1aeoyo0cnSrlI7CU0BQoYGy1BgGWbiv8EeykIBDQFNQ0BTYOjgz4WeqNr2cxycHj/GbG4M83DxReO11gE8eH09BDwzxrIFMQKEtCFmg9kP9+xtndF9JCyDUpU4wk99etACmgoqVJ4aMKfF2KSTUasbFC7uwPmmh/It1RHGOTEs0yvRMWbH0JQFqnPUFrdL3DK9Ena3Dy09we9zfYkcdo8PLm8Abh8XtajLYPeCb79fAEkFvC+M2Saekbme0gEumGYcjNen9vsjFtAoVUuglrIQMjS8/sBEXwxXXJfaqNWNv54axtbG0tQmnyGIESCklWKlGLWFMnSk2N1JMOH7PxnDzxvggENdBmhlQiwuUaRFgz8Z1tdoQQE40W+Gw+NHmUaCMrUEBpsb50ftYGkKSklQA0gmYrCqQg0BM6EBxAUFzbz+oHvC4fHD4vTCy9NHQcU4MTSWqXB22BqhB+TngIUFsojFfHGxAhSFiL7TZ4dsKFWJoZEGe0ing26DA1qpEAZH4oV9YZEczV1GtKcxWJ0JXL5AWO3DVIoUIhQqRJAKGVAInsbOj9pChXFPvteOzywtglCQu3aS0yFGgJBWLqktwNcurcb3Xj+V0tc3lvMTLjPYPTDYPagvkcPlDaBrPPMuoqmaOwqxABVaCXoNTvQbL+amewMcxu0ejNs9KFKK4qZoTuLmmVETTWl0fbUWh7tjN3BRSi66pJaXKRHgOJwaiC3bUKaW4HC3EWsq1Tg/ap9xFbM/wKFaJ4WhJ7ERGJoS72jpNs6aDmFTmUx5nUqxQoSrlxTBH+CwvEwFh8dPjABhbvPOmREAgEIkwO2X12BFefAX3+Hxwe724/22ERzsNEDI0FCKBVBKWKgkLIqVIrxxbDCpZ50dsgWlCKq1OD1oyaicRK/h4u4v2EIz/rP4CrI4PPzmPHWnL2QoNJSpEjZu6TM6sK5ag0GzK2EWjVrKom04aCBaekzQSNm4shh8OTNkxYIiGc6PxD8d9hqdWKZX4tSABRyCPRjWVQdPBLNZ3GbY6sZdm2pRW8hfxjubECNASCs2tw8XRmz4l88swq0bq6OKY3398pqoX/uXE4NJGwEg6IM/1GWAVspiRYUq1Mox3RQpxBg08w8K8l24+O62J0XmJCyNqgJZ3BOTRspiUbECZ4Ys4Digz5i4krZWF35Po8MLo8OEVRVqXieaWDg9fnSM2lFXKEuY+imYpiMRbMajQvuoLa8F4aZSWyjD3zWUwOkJ4MvrK9A97oBOkT/9A6ZDjAAhrdAU8N4DV0KUwnF3pul7QSlmM9ZWa3A4A26EeD0DosEn4EsBMPE0AmanFwqxAGVqSUwlTpoC1lVrcbTHGOp9YOLhj1+mV8Y0Kh1jNshFgpROWXqVGBVaKfqNDl7G7nifGUUKUZhL5Xi/GdUFUtAUhY480uGfjoCmcNkCHb52aTWuri8KXV9YnL7GOpmAGAFCWpEKU/+VCqTpzH+4KzP+5PYRG6oLpLzjD3HUnENopCzvHgK1Ojm6xu0xDYBOLoROLoxovJNo4ZQKGRjs0U84pRN1GgKG4t2vVycXoq5QjnG7G+dH7KEU3w01WozZ4ruvOADVOlmEX33ye16kEEEnF0EiDKZz+gMcHB4fDHYvRqyurNYBlKklqC2Uoa5QjqV6JT6zpBgamTB7E0gTxAgQ8oZ0GQEg6EbIRLPzQoWItxHwcYmtgN3jg4Cm4EuweqkkgrifZZleiX6TM2rP3QAXrDGI5U5pKFNGLPBKcbBO40iPEYNmF0QCCjq5EGO26KcKxcR4m9uHM4PWqIt9+7AVLEMllK+OJ2gXLfA6CYVgEFYjE0ImZEDRFE70mdMmcU5TwNZGPb6wpnxC5yh/grszgRgBwpzlUJch7YZgyOLiLbHg46Gs6vZxWFQsDxV4xUIjEcLsjHTHqCQsFhcrEn/GGFNRiAUYtV5c2IUCGisr1DgzYA6r0Hb7OCwvkIUZATFLY0mpEv4Ah9MD5oQnL4PDi1WV6oT9FQx2Dy9jMR0OwSDs8BQjoVeLIRIwMVM6+bK2SoNHbmrA0jySMU8XxAgQ8oZ0ngQmSbchkIsE6DU4wdIUFBIWChGDQqUYHl8ALE2DpoP5/BSCRUVSIQOvn4PL64fdHcwosk7zrauliV0IUtHFXWeFRoJStQQWpwftw7aEn40CohqtVRVqdI87whbImgJZTBXQlm4jagqkUEhYMDSFMwMWXg1zpuLkkQnVoFemTR9qwBQ8xaTapaxAJsSuzy7BzavKQEdrfjAHIEaAkDdkKg3wUJcBy8uUKQmNlWkkYXUAsomYhzfATdQqAEIBE1XGuEYnCy2wG2q0oTEUgvr3chELuUgAAU1hTZUaDEWDooLG0D/RftLlDcDu9oVE4dZUaXCiz4ReHtk+k+jkIozawl0ojeWqiIyfYGP26PGGJSUKyMQCnB20oHMGNRlnh+LHVUQCCmNprhh2+zi0dBtRrpGgWCmGgKbAIahb5PUH4PT6YXf7YXZ6Q8FvkYDGl9dX4r4ti3Le/jHTECNAyBsyGdQbsbiTkiheVCwHTVE4O2TF6ko12kdssLp8UXeDYja6PIQvcPFZU4XfOABmp++ie2d4cvdrijmfco0EQNBAeJJ0k2hlbJgRWKZX4njfxTRapViARcWKqBW6FVoJZEIBLC4vzo3YkhaVi0asuIpYQKOxQp1UP4JkqC9R4NI6Hf54fCDsBFNdIMU/b16AddVaiFgabm8A5RophDxVWGc7xAgQ8oZMtrsetroTuoVqdTIUKkQYtbrDfPRHekwokAlxWV0BHFHcKmwMjaCpMYEegwNlajH6TdFVQBPFGCZF5s4OWlChkSR1EpCLWTTolZAKBfD6A2EngDWVGlwYs0UYAKGAxqoKNVq6DZi0m+nKuDrVbw6LqxQrRChVSzBmc+NwmgP5k3xmaTH23LoWQLBOpXPMjleP9mPM5sZ3PrsEMtH8XQrn7ycn5B2Zrgo91GXAqgo1AuBgcwWrl9VSFkqxAF3jDnSM2WOmU5ZrJGgbtqJUJYl4T0BHNwLTTx1lGmlMI3Bh1B7XTTL5vXF6A6AoJKX/L6AptEzzsVdoJFBK2JB43FSWliphcnoiUk3Pj9jiZhnxxeENYGWFGoMmJ6p0MhzvM2G4N7NNgg52jMMf4MBMnORqdDLc/5lFGX3mbIEYAULewKW94WEk0/3gQ5b4+vwLiuRgKODYhPtEJ48SxI0RL5weBDUm8HVP1fmZzlTdoB6DMymJ5qlFbqsq1DgzaAmeJKadJjRSFjW62JXIxom+A9ONA18YmkJdoQwaqRBilkZrb3gmTyaxuX0YtrigV0ca8fkOMQKEvCFXDT9iMalvPxWOi1zxo7mxqgqk6J62q28fsUErE8aUSp4umTAV77TKsyM9/OUcBs0XF3uT0xPWxL1QIUKpSgy1hMXRXlNCw9Laa0SBTBjqOxCP9TVaXBixYdzuCbbfDHAhN9vKCnXCr08HT3xpJZbplajQSlOqYp8PECNAyBsykSI6EwRR9Pvbhq1YXKwICa0BiFroVawURxgBINgfOZYRMMQoxAIAjy/SBdNtcCSUc9BKgwVeBTIhipViKMQMdHIRrC4v+o1OjFrdGLW6IWQoaGTChKJ4bh+H5WWyhEZAzNJhAd7p36IxW3ZOAB5fAAuK8lu2IdfMj/A3YVaQbyeBQ10G1JdELiABBLC8TAm9SgyaQoSOPwDYYiymsRZZMUujO07HtGi6RQa7B0tKoy9wcpEA62s0WKCTQS5iMG734PSgBQc7jWjuMuLskA1W98V7evwc9FHiHdFo6TaiQhN/bJVWGvf9AZOTd1vNmfD4O+1wRzGghIsQI0DICziOw/nh2Dr3uYDjgHG7Bwpx+IG5fdgOhqJDmjhGuxsNZUqsq9ZgfY0WKyvUsDij75Tbhq1QR8k7r9LK4kZEbK7oC1lzlxFLS8OrWFeUqyAU0DjUaUS3yQGbm98ieLTXhFKVOOE4DsFewPFQSeK/H+CQFf98v8mJFz/tyfhzZjPEHUTIOU6PH7teOY7XWgdyPZUIRq1urChXhQLDk4zYXKHG8gNmNwaiSExrZUIs0yvh8vrRa3RiyOwCxwELCuURKZkqqQBFEx2pxCwDCUtDwNChbmKBQABlPgncPj+cHj/snmCdgT/AweQMyixopEKUqMRhczXYPKAo/plXOrkoYTN7IBgon+4Wm4ovEICAplBfqoCEFWCyKdpUF5FawqKb37RmxC8+OI/PNZaiSJnYwM1HiBEg5JRegwN3/U8LzqSpnWEmONZnjsiRHzC5EtYdGOwenBm0hPR2ytUS6NViSKIorfr8XExhtHjpoAoRAwoUNtYVoLnTEHEPb4CLkGaOhyRG4Vs0AjHOLnWFMrh9AZSqxBFtQiu1EozZPFCK2ay5/6wu35yv+p0JM3IHPfroo6AoCvfeey+v8Xv37gVFUdi2bVvYdYqior4ee+yx0Jjq6uqI9x999NGZTJ+QY/adG8UNT+3PawMwyfE+Myq14e6L9hErxAmqSsdsHtQVygAAfSYnDnUZ8eG5UawoV0Eru7gwjVhiL9LT3VFTsbr96Dc5MWJxwRmjTWVBtLTWWMToYxyN9mEbVpSrwq7VFsogFwlwesASVtDWWK7CgkIZegxOgONA09kLDl9SW0Ayg+KQ8kmgubkZzzzzDBobG3mN7+rqwgMPPIBNmzZFvDc4GN5N6i9/+Qt27NiB7du3h11/5JFHcOedd4b+rVCQqP9shOM4/PLDC3jsr22zpm2g2xcARVGQi5iQj51v3rxOLoroqHWszwyFWIDVlWqcH7GhzxS7AlgmEgAJdvICJvYiJ0uix8O4zY0SpThh/cQkYzY3GJqCPxBUQ/UHuKDba+J9rUwIvUocJlPh8Abgs7rhzdJR4IpFhVl5zmwlpZOAzWZDU1MT9uzZA41Gk3C83+9HU1MTHn74YdTW1ka8X1JSEvZ6/fXXcfXVV0eMVSgUYeNkMlkq0yfkEI7jcPdLR/Hjt2aPAZike9wBlzeA5WWq0Ang9KAFclH8XWaszmFWlw9HekxYUhJfnnhSPC4ewjiZNsmoX14YtcPm8mJ1pZrX+H6TC6sq1GjQK9E9bseFUXuoAEwnFyLAcVEVQQsVoqz8/JUSAV4+3IsfvXU28w+bpaRkBHbu3ImtW7diy5YtvMY/8sgjKCoqwo4dOxKOHR4exptvvhl17KOPPoqCggKsWrUKjz32GHy+2DnNbrcbFosl7EXIPQcujOPNE8n3Ec4XfAEOJ/rNaCgLukGsLh+WlMZfxBO1ZfQnWA2FMbSJpsIkUWiWCJvHjyM9JqypUkPCwwD1GZ24MGKF23fxcyhEAtQWymGK0TWNT6+FdLCgUI6zQ1YE8i3/OI9I2h20d+9eHDlyBM3NzbzG79+/H88++yxaW1t5jf/1r38NhUKBm2++Oez6P//zP2P16tXQarX45JNPsGvXLgwODuKnP/1p1Pvs3r0bDz/8MK9nErLHiwdnb7pefYkCdrcPvUZnaHetlrKwu31YX6ONqX4ZL27A0hTaYrSLnIThkU9Px/Hl21PoDQwALd0mlKnFEKvEcRvED1lcIbdYWFOaOG6yVPoVJ0tjuSpUAX3LxqqMP2+2kpQR6O3txT333IO3334bYnHidCur1YpbbrkFe/bsgU6n4/WM5557Dk1NTRH3v//++0P/39jYCKFQiH/8x3/E7t27IRKJIu6za9eusK+xWCyoqKjgNQdCZvD6A3jnzHCup5EyDo8fNrcPa6s0ONRpQKFCBAoIafCvKFfh3LAtIpNHIxUCiL6ILtOr0Npniv9ctw9ykQB2jy+mCyXeYcJo59fDOBr9pmAq7IaaYCZUrOcc7zPjkpoCdIzZeElB2z3+lLqH8YWmEKpqrtRKUa6JX7w2n0nKCLS0tGBkZASrV68OXfP7/di3bx+eeuopuN1uMFMCVBcuXEBXVxduuOGG0LXAhMa6QCBAW1sb6urqQu999NFHaGtrw+9+97uEc9mwYQN8Ph+6urqwePHiiPdFIlFU40DIHRdGbWnr95oLegwOrCxX43C3EbU6GcxOb5h8wrE+M2p0MtjdvrCUzHga/NFE8xQiASoLpKGFv2fcDo+fA8cBciEDuVgAmUgACcuAZWiwDAWFWIBSlThqjv+ozc2rj3Es/BxwsDNYPT1u92A0SpDa6fXDzwV4p6ICwdaYsXoWz5TVVRocnkjpXcUzvjFfScoIbN68GSdOnAi7dvvtt6O+vh4PPvhgmAEAgPr6+ojxDz30EKxWK5544omInfmzzz6LNWvWYMWKFQnn0traCpqmUVRUlMxHIOSQ6Tnjs4n1NVp0jdnRbbBDJmRiSk6rpSxEAhpKiQBSoQBiAQOGDjZyOT1oCdtJqyQCnB60oEwtQaFCCKGAwbjNjQujdpyaFkxdUqrAmUErbB4/bB4/gPDFtqFMiUGzC7U6GXQKEbrH7Rieknaqk4t4Z/zE4uyQFQoRg5UVarRGEa470mOK2zNhOkpxZowAy1DomvLz+cKa8rQ/Yy6RlBFQKBRoaGgIuyaTyVBQUBC6fuutt6KsrAy7d++GWCyOGK9WqwEg4rrFYsHLL7+Mn/zkJxHPPXDgAA4ePIirr74aCoUCBw4cwH333YevfvWrvLKTCPnByX5z4kF5SEOZEke7jQlTGiUsg+O9JkTzcKyr1qBILkKVTgavLwABQ0EsoNDcZUK/yYn+OCmiQHDBjIdrokZgak+EBYUyFMhFGDQ7IRUKZmwEgGBdQmuvCWurNDg1YAlzffkDHHQKEW8jwCfonAorJk5rQDCOc1kdP1d0tjjaY8SqyvxZt9JeMdzT0wM6RpONeOzduxccx+HLX/5yxHsikQh79+7Fv//7v8PtdqOmpgb33XdfmM+fkP/0GVPvTZtLRi38ctrrSxUxG6+7vAEMW8P189dXa8NkneORSLXTFUVg7vyoHecnArrrq9XYUKNFr9GBAZ6LdDwOdxtRrpaAFdBhjeqP9ZpRVyiLG0ieRJSh9o1Gx8Xv1Z2bavOuQfyP32rDtlV6/MO6ylxPBUAajMAHH3wQ99/T+dWvfhX1+l133YW77ror6nurV6/Gp59+msLsCPlEdcHsqutQiARYXq7CJxfGeY2P1w/A4YnMhklGOvvCiA0KkQDWGFk1tij3n0QkoHGy3wLHxGlhQaEMKqkQx3pNKccJgGAFtEhATfRHvui+ErPxd/hFChFqdLKQLlK6mTwJ1RbKcONKfUaeMRP0agke/MMJjFjcuPuaBRn7PvCFqIgSskaifPp8QSVhsaFGC4CDxcU/sybWH/P6Gm3UnbE9zsI9HQ5AbZEcDE2hUivF6srgzr5CK0GJUghzjHx8AFhergoZACB4QmjpNkIrE2J9jZZXMVos3D4OZwYtYcVlpwYsaCiL/Fnr1WKsqdRgzObGwU5DRnpKS1g6FHexu31516MCACom5Ed+8vY53PnC4aiB9mxCjAAha+S7EShSiLCuWgOX14eDnQZY3X5IWf6H5ZFpPncBTWFdtSZmyqQ0CTkHABCzFBgqmKV0pMeEg50G9BqcsHtiSbkFUyX7Y7jhJjN5AgEOa6s0WFqqiHuaAYLSQnqVGAuL5KjRySBhGfi5SO0jxxT56iKFCGuqNBgyu9DSYwwJx2VigZ4qTz1sceOVI/1pf8ZMqZiSrvrOmRFs+6+Po/akyBZERZSQNZaUKlBbKEMHD39xNqnRSaGVidDaY4xIcRSx9MSpAKGFtrXXFPWPtt/kRJFChEqtFBQVPBlMbe04nXhVvtHoM7rgiRJ1VooFMZvVrKyI3Yt4VaU6ZKAmA6kiAYW6QjkUYjbMl+73B2B2edFrcIT6KABBI7O0VIESlRj9ZmdoF94xZseKchXGbB7YPT60TJPOBjJTNayeVpPx5vFBfHl9fvjeJxFNU2rtNznxb2+cxCM3NYDlUR2ebogRIGQNiqLwlfWV+MGbZ3I9FQDBtE0g6L7oHIu+W/b4AmECcXWFspi7Nq+fQ7VOikOd4Qveqgp1UOlzmoFxxZCHjkW/0RlVFjrWiYKiENPVUFcow6ko2VpuH4e2iT7AfAhwQOe4A93jDuhVYpRppBizujFgdsLt80MmYmJmPqW7ZqRGJ8PRaT2hD3Ua0DZkxeIoHeIm4TgOozY3zA4vyjQSiARM0gY6Hh2jNtz3u1bUFcrRa3SESZJP8ttDvegzOvHc19Zl3RAQI0DIKhtqCnL6fIamsLJcjXG7OyIXPxrTPRZamTBu5ku/MXLBO9prgpSlsbb6YgETAIynkCNfqZVGGAFxjB4AK8tjN6IvkIsgoOmYTWGSoUGvRHOXEXaPPyI99Fwcg3J60BKqa7A4vegzOCZqIJJHQAcX8+lxbo8/gF2vnEBtoQz3blkYVjnc0m3Ann2daO4yRGRfFciEKNdKsW2lHk0bqiBMMZPJ5PDgqffP41ifOaIx0XQ+ah/Dbz7txu2X1aT0rFQhRoCQVSq0mW8pGIvJZustPZE7sViMWF3T/h07iLemShPV7QEE5ZMPdxnRoFdiyOLCmM2DQbMz6UreaDvUWDvHqamS0znUacC66vTkqsfqRCYTJm7kMrWuAQCKlSKUKMUQswysLh8ujIYL08VidVV07aZJTacjPUa80TqA7WvK4Q8E0DXuiCtvMW73YNzuwbFeE/7r/Qu4clEhVlepIWRomBxenBowY8DkwqaFOmxaVIjlZaqwn43V5cWo1Y1rfvJhwrlP5cn3zuOLaysgF2Vvaaa4TITo8xCLxQKVSgWz2QylMr8DlHOdNd9/O2Hee7ooUYphcnqwqFiB7nE7zM7khMtoKhjgnfTFT+8wNolaysIf4GL65qciZWk0lAerbvUqMbrG+dVPMDSFEmVkMdb6ag0OTZvTomJ53F04RQEaiRCGOIaCD8v0yqgnKpVEAIfHP2NtIJYJxiiUEhb9RkfUQrSFxXJcGLGFnQLkQgY1hTKcyFKVulTIoKpAhs8sKcK1y0rwwoEuvHZ0AJ4kFVwB4IkvrcRNK8tSmkcq6xw5CRCyzqJiBQ508Mu9TwaVhEWZWhxswoLgTvj8iB0KEQOL05uUAZCLBNCrxTDYPdBIhWgfCS6orT2mqH75Op0MLTECsNNxeAM41GlAkUKEkiSMwOpKdVQDFC01VSWJvwtfXKzA2TjqpXqVGHq1BO0jNphj9EMAYge360uUCZvt8MHr58LmWVsog04mwpkhC6wuH1iagsPjDzMAFRoJAkDWDAAQFBc8M2jBmUELfv7e+Rnd68WDPSkbgVQgKaKErHNpXXrjApVaKepL5DA7vTg9aEVzlxHNXUacHwm6Gaxuf1ilLh/qCmU4N2zDmM0TJvLmDXBweILS0ZMVr/UlCt4GYCpmpxcsTfM6+kuFTMgQTWf6XlsiZCCgKZTEaawea/EunEiTHbK4cLjbiPo4AdWSaR3DptKboerwjlE7DnUZ4PEFsLZKg9VVmrA4TGO5Cga7J2psZrZwqNOAYzFiOZmAnAQIWefv11XgiXfbZ1StCgRdBasqNWjpMkTV65mkWCHiZQTKNRKUqMRwevyhIJ5YQKNrWuaQze0P7eTLNZKki56qC6QoUoghETL48NwoqgukkIsYOL2BsF23RMigSiuFUsKGlEgFNAWfn4PN7cOI1QWjwwt/INzlsEyvxIGO4C58cXHQlXJuOHxHf2ogGJSd9McrRAIs0StxtMeI5infq64YQnkAUKmRYihKPGCZXoFTAzMPOMfD7QuE0lon4dPqc7aQzQIyYgQIWadYKcaX1lfgN5+m1mBGKmSwVK/EmNXNS7u+VCWJawQqtBII6KAGTt+0HWRdkSzmgjZidcPm9kHM0mjQKyETCTA2oQI6nXKNBGVqCfqMDnSNO0IuoMmFSykWoFApQqVWAgFDY8zqRq/RGddlAwRrBGgERe7EE6mNYgGNFeUq2D1+GB1eXBi1I8BxqC+RQykW4vSgBTa3DyKWDhnSWE1ghq1u6OTCCLXPSq0ULd3Rv/fCOP2OM4k/wEErY2GYQf+EfEEtTRxUTxfECBBywq0bq1MyArU6GVw+f1iqZTxUEhZiYWyv57pqDY73mcIyUHRyIWRCAYatLkgSVAwvKVWipdsYtvAoxALU6mQQsQxYhkK/0YmucUeEgQGCOv0NZUqc7LdAzDIw2DwwxpGAmM6iYgWap+yIKzQS9EZ5jkbKws8F+xcEAgEsLVVCwjJYXalOuHsuU0vCjICApsAyVNTTl04uxIl+E4oVImhkQshEAghoCqM2d8aLBA93GyEXMlhXrcHhbuOs62E9lWxWEBMjQMgJC4vkuHJRIT48N8r7axrKlGgbtPJS9ASAMo0E/UYnPu0wgEIw/bBMLQU1YRPMTm9EoFUnF0IpZtExZgdNJe7/6/JGBputLl/InbRMr0wY+O0ataNCK0GvwYnaQhk4IGZv3qnoVWKcGgj3yevV0Y2A0eENGZcFhTL0Gh2hTKY1VWp0jtlj7qCP9ZnD2meurlJHFMQpxQJYXD7UFcpxsNMQoZi6tlqTshGI1SwnGjaPH81dRtQVBsUK+aiZ5iPpkP3mCwkME3ICRVF4/B9WolzDr25AImTg9gZ4GwAAKJ+iI8MBGLK40dJjxOGu4Kt9WgqlWspCLhKE/OQBDrDFSfksVIgS+r5PDViwokIVd4zN44fPz0ElYdExaodcJEB1Qfx2iDQFyMUCOL3hO8ZEfQmAoIBciVIMyYTaZ0u3CS6PH6sr1VhfrcXKCnXE1xzqNKBSK8G6ag38fg4rK9RYUa5C48SLZWgsLpbHbLaTKnKRAG6vHzU6Wdyq3+lcGLXjwqh9xgJ5uWJ/+1jWnkWMACFnaGRCfPUSfg3AG8tUE716+ZOMN6BWJwPHcRG79kGzE7GUfmt1/KSxh0yuhNr5g2YXSlViCGgKfUYnug0OrK5UozJGcd26am1EHUAw5sAvK6Z9xIbaQinYiSb2Dm8AR3pMONRlQGuvCXWFMmyo0WJttQayiUW0x+AETVFo6TGhtdeEY31mHJ94jds9YBk6ZkDzZJ8ZDWVKrJtyv1iopSzWVWuwauLzGxxedI7Z0TFiw8IiOa/PN8mhTgOkQgYrExjifOOPxwfgTLF6OlmIESDkFD5ZEMv0ShzuMuBYnzHJgBk/M7CgSI4RqytqHYHN7cfysugLCN80xGGrG+uqNVhULEelVooCmRAMTWF6lubZIWtoF85xwXaNAyYXNtRow8bWlyii+vH5nqomOTVgjfnZLozacbDTgMNdRrACGuuqNdBI2Qj301TidQpz+QI42W9Bc5cRXn8A66o10MqiG3WTwxt0qfWacHrw4kmrQC6EN4XiqzGbB629ZjSWq1CkmB19x71+DtYkZMxnAjEChJxwrNeEm57aj+c/7kS5WoINNVrUlyhQX6IIy5tfplfi3LAVfi4obraomL9LwMNDbmBxiQKDJids7ti7rvZhK9ZVa1Cjk2FpqRINZUosKVWgj4frBQi6bowOD4bMLvQYHBi3e+APBHVu5CIGZWoxFhbLsaI8uCBvrNOGvtYX4HCw04DFJQqwDAWRgI5avMXQVIR7iw9HekwhldRYmBzB2MniEkXc7xNfLSSPn0NzlxEOd7DeQsIy0MpYFClEoVOXVMiEFYAt0yth9/h5F9ZF43ifGRanF+trtGkViMsELENBE8NIphsiG0HIOn1GB6587INQ7ns0dHIhFhbJcbjbGCY9wDIUFhUreIm/VRdI4y4aS0uV6Bi18W7xOJVLajQIcBQOdSVOUZ1MA50aXE1EY7kqohBrRbkKYpbGwc7IzKjVlbElo/kQq3n8JFoZC7vbF1PHh6aChigVmQitVIglpQp8PNHBTSygQVMINcJZX6NFc5chrdk+1QVSsAwdswAv16ysUOO1nZcl/XWprHPkJEDIOm8eH4xrAABAr5JEGAAgeEw+NWDB2ipNwkbl8TIslumVaB+xpmQAaAo4NxKsXE0kwraoWI7mCUNxos+UUM5hkvZha0Rw+FifGQ5PAMy0TayYpeOKxfGhZ9yOqjjB6AWFirhCbuUaSco6QeUaSVgLT5cvAIc3AIWIwfIyJQ51ptcAAEDXuAPtIzasq9ZAkUWxNr58Zmlx1p6Vf5+ekBLnR2yQiRiM2zw4NWCG1eWDgKZgsHtgcnohFQpgtHvACiisrNDgc42lCXvBZoKfv9uOn759Lu6YxnIVzgxa4i4qh7uNqNHJ0GtwxKw8dnkDUXV+GvRKtA1bU1q0SpRi6OQsegxBV1BzlxEbarQ43G2MMGxqKQuD3RNyazi9ASwvU/M6PTi9ATg8/ojipxP95ogTxfIyFS6M2LG8TIUTUXoEJEInF0IhZuH0+KCWshHpqUUKUYRO/3SKFOLQ9yQZanUynBu2RkRvqgukcHkDGdf/ae4yQitlZ3ySSjc3rsheb2RiBOYIZwYt+NZvj/Ia+5tPe/DUe+146iur0RAjMJgJhi0u/PdHHXHHrChX4dSAhZekROeYHWuqNGBoCi6vH2NWNwYtrrBdY6FCGGYESpRidIzaUjIAa6o0ODtowZDFhVWVahydWDQOdhpQphajTC3B+VE7DBMKqZUaKY5PW5SP9hqjVuBGY8TqxsJiOawuX9h8Tw9YwNIUvBNtISdrHQwOD9ZVa3Ci3wyXl98Jp65QBtNE9g0QrN+YlKWYpKogsofBdFItbqJpKuI0trBYjn6jE44sZccYHF4YekxoKFNizOrJao5+NKoKpKjQxk8RTifEHTRH+MzS4qTyobvGHbj5F5/gfz7tzkjD72h897WTsMTJu0/GAEzS0m3EoU4DjveZMWB2gaUp1OpkWFWhxtpqDRTicPeLXi0Oa7rOB5WExYpyFVq6g41TAMAdkZ/vwqEuIwx2D+pL5NhcXxRhAICgO6uGZ2opALQP27BqWt6+ze3D4lIF9CoxTk/L1mnuMkInE4WKpeLRWK5Cn9ERJuvdPmKDXMRgZYUaApqCViZMeArQyoQ4NZjajl07LdtLI2UxZnVnzQBM5WS/BUaHGxtyHDiuLuD/+5EOyElgjiBmGVzfUJJUY22PP4DvvnYS/3u4F7dsrE7JRRQIcPjLySH0GBwwOjww2D348voKrKkKZpyYHB68fXoYb50cwrtnR2LeZ0W5EqcHkzMA0T8TF1GwNHnUj9ULIB5LSxUYtrgjukL1xVHJNNi96Bkfi+gkNsmRbiO0MmHoxDAdlrkYYF1XrcGZQUuEOJpWKsSgyRXVoPWZnBAJKFxaV4BPO8Yjum0BwTTTU/3mqNIPQxY3hixuyEUMVlWoYHR40TFmj1nFvLBInrJw2/TH1xXJeUuCZAK3L5iNVaWVQijITeA4UaFguiHZQXOItiErrn9iX8pBNLWUxfXLSrC6UoP6UgXK1BJoZcKoevUcF1xs/88fjoctrEKGxi+aVqNr3I597WP45PxYwoV9RYUKJ/vMWFudGRVICsA19YV49yx/iQqWobC6UhNzPvUlsfX4G/RKnJzIXoqVETRdCmFhkRwqCYtBswtCAY1CuQg2tw+np+ywJ11Q66o1uDBig9HpjfmznjQaC4vksLl9Yc9iGQpqiRCjtsQ1GlM/54IiGQpkIhgdHrSP2MBxwXvJRAJeMhfRYJngya1t2IYCmRBmp3fGG4F0sqZKjUGzCwNRmtlMp1wjwYDJGdXoJsO/3bA05RaTqaxzxAjMMb798jG83NKXtvuJWRoFMhH8AQ4efwAeXyD033SwqkKNY32m0B/O2ipNhETwTFk3sSNfX6PFkZ7IjKPpVGqlYGgq5CePxqTo23SmL/oMBdQUynF+2o5SJKDh8QewvEwFfyAQkp+YegqYDktTuKSuAB9NSArUFcqiauOwDAUBTYUkJWRCBktKlaHva1WBFN088u2jpalOopayWFAoh0wkwCcXxmbUQYymghXQNEVlpNlQOlhSqoBCzMLh9sHi8sHPcZCyDJQSFhSAXoMDw1Y3Lq0rCMt0SoWnvrIKn2tMLTBMOosRsOuzS/DWySFY3cm1UYyFyxvgpUeTCqsndrZTl48jPcaUs1yiEUzRDC5+BzsNqNBKIBIwEYvyJKsq1Dg9aE7Y13a6PINUyKChTBWx6/dzgNPjg4Rl4PQG/dwFMiHqiuToGbdHLLLxFtNVVZqQAQjeRxTVCNSXKMKyauwePw53G7GoOHjaELMMegyOuCdGlqEwEidAanJ4Q0ZFJKDQWKaCkKXRPe5IWgs/wAXlHQrk2SmOSoUzg4n7IwhoCi98fT3ODFrxzL4LePPEYFKncpahUKGRolSV3T7cxAjMMbQyIW6/rHrGLe4yTaym7AEumAaZiv8+GtP/CHsNTlAI7tiPTjsV8C3mmirXLGEZNJarcHrQEvNr+02u0AlHJxdCLhLwLhqbZE2lJoqBib7CxHJHTNUainWKmGRVlOfFwu3jwoLg1QVSVGqlGLK4Qm6jRCyPc+qYLSzTKyFgaCwvV+Gpr6zGvSM2fHx+DEUKEYqUYqgkAjz13nm81joQ8bWrK9V46iuroVdn1wAAxAjMSb5xVR1ebunjLb+bbfi4fFq6jTGbmPOlUiuNGtjjENx5lihFKFFJcGbQgqWlSt6LXolKjF6jE9UFUjg8fl5xjMPdRly2oADtw7akpQ9kQgbnRiJ3ouMxfPp8MlsK5NFPEcBET4A+U1JznErXuCPUzUwpEWBBoRwcgPPDtpgn1MAc8EpfUhveNnVBkRwLpgne/fTvV6JALsKz+zsBBOXA792yCDevLoOAyU2yJjECcxCpUIB/u2EZvvGbllxPJQK+O/wAB3SP21Gu4a+MORUJy6BQLkKPIfaCO2Rxw+MP9qr9OAk/rtcfgFYmhM3t45XvDwRdNOeGrVCI2IQ599NpKFNFNTTd444wN9MkMy0CrNRKZ1Q4JWEZnJkIaFucvtC9KAD1JXKoJEIMW1whY7igSBY1vjLb2MKjypemKTy0dQnWVWtQqBBjeZkKwgQKs5mG1AnMUa5bVowtS4pyPY0wknXx2Nx+BDgOSnFye5VyjQSFCiFaEuS3V2qlYGkaH18Yx8pyNUpUsRuzT8JQwcVXK+NX8AUETz7nR6wYtQart4uV/JUsFWIBTsWIj3AAqnWR6YQOHvGgWGeF+hLFjCtn60sUUWMbHICzQzYc7DSga9yBKq0UKytUs7oD2CQlSjFWV8aXEJmEoihc31CKNVWanBsAgBiBOQtFUfj3G5eFGofkmlR9/AMmF/RqCQQ8i3dWVqhhsLkTShg0lCkxbrvY/aq1z4RxqxtXLNRBK4ut77OgWI4anSxmYHkSkYBGpVaK9dVBSYnJZCrDhO4+Xw2hpaVK2OIUTinFkfeJV5A3STT3C0NTWdOwB4BugwOtvWYoxWyo34JOLoyQ2J4N3LKxKu+VSWNB3EFzmHKNFPd9ZiH+489nczqPmQZ5zw5ZsaoyqHIZa9cooIN5/fF0eSgKIanqaPPxBjiMWF0w2L0oV0tQpBRBwNAITERaKQpQS1iM2NxYXqZEgAs2NxezDEQCGv4AB5vbC7WUxacdRvQYHFHdUX1GJxYUyeH2+ePKO6gkLI4n8M0bogjHJZudM8maSjUOzTAYLxLQODuUnGvnaK8JCrEAC4rkOD1gQW2hDAMmV4SbK18pVIjwj1fU5noaKUOMwBzn9stq8MqR/piFTZlmeqVrqhztMWFtlSbUVKTX6AxV3NbqZKBpxDUAerUYFOKn+k0NRPeZnFH7BUTLqqnRSdE5dnGx59P96vyIDQ1lSpwdtMYsjqorlCV0zbQP2yLiJk6vP6E+0fQn6uRCnExDWu5SvTKkqZQMVpcv9L2fbAuZbAZVrvjM0uKcBXXTweydOYEXLEPjP25eHrNFYiZZXx274jYVDncbIWYZHOszw2D3QMLSKFKI0DFmx/mR2OmOpSoxXB4/+hNUfboS7DwVYkHUjBq5KNwlEytrZzoMTWGZXhFydYkENBr0Sqyv0aK6gH9wtlgZGctItoNWmUaStKZSNJye9NSnDGaoNiXdCBkaX7+sOtfTmBHECMwDVldqcM3i7AWJGZoK7uQyoAFzsNMQEmBzegMJM23UUhaVWikMCWQN1lZp4ubNA0BNDGGv6a5gg8MLMRv/T0uvFuP8sA3H+ixoLFNifbUGAIeTA8F6g2TSSI90G8P0ZqoLpLAmiAswE7sCmgLWV2txrHfmpwCaAkYswZ9HrS7Yo3gNz2DpdJSS2eGk2LGpBguK+He7y0dmZAQeffRRUBSFe++9l9f4vXv3gqIobNu2Lew6RVFRX4899lhojMFgQFNTE5RKJdRqNXbs2AGbLT+7AuUjd2XJZymgKTToleges2OZPjPyHBqefYarC6SgKSrhaUQnF4ZSGuORqInNVIoU4lAT9+mIBDSEDA27xw+hgIbV7YfbF0hYpRwLDkHDK6Ap1JcoMGxxhYrZYsFQFFZXqlFdIOPV3yARKgmLlRVq1BbKoZGy6BgL9ihu6TFifU3yhuDUgBVVWgnvAHouKFKIsPPqBbmexoxJ2Qg0NzfjmWeeQWNjI6/xXV1deOCBB7Bp06aI9wYHB8Nezz33HCiKwvbt20NjmpqacOrUKbz99tv405/+hH379uGuu+5Kdfrzjg21BfjnzQsz+gwBTWGpXoljfWYMW904NWBBfUn6d0nH+8wJDcGGGi36jI6YSp1TKddIQxLR8fDEaHIeLYBZrBRBJWGhV0e6alaUq0M7/VUVarSP2CASzCyL68KoHeuqNegas4c0g+Lh4zgc6TFFKK4mQ5lagvU1GtSXKGBxenGkx4TD3UYYp526DDxTaafTbXBm5PcnXfz3bWvD+mHPVlIyAjabDU1NTdizZw80msRW3u/3o6mpCQ8//DBqayN3pCUlJWGv119/HVdffXVo7JkzZ/DWW2/hv//7v7FhwwZcfvnlePLJJ7F3714MDESWYBOic9+WhbhuWWba1k0agOml/+IZLm7R8AW4iErMqaybiEUk0rgT0BTWVWvi9tadSrT8e5pC1Ayg5i4jxmweKMVsqIF8Y5kK1QXS0M5bJWFDwVh7GnzpBzoMaJzWeyDdLCySY0ONFuUaCfpNThzqNOLsUGRnsKmcH7VDm2LT9NMD5qT6ZGSLukIZGsvVuZ5GWkjJCOzcuRNbt27Fli1beI1/5JFHUFRUhB07diQcOzw8jDfffDNs7IEDB6BWq7F27drQtS1btoCmaRw8eDDqfdxuNywWS9hrvkNRFL5/UwMUSRZfJUJAU1gWxQAAwOlBc9p3SyxDgaWpqL1hG8qUCfXoixQibKjRQimOnioai2inhUXF8rhpnmeHrHB5/VhcrMDxfnOYr39xiTx0z1MDQemKmXKo04BVFeqEriu+eQKTabXra7QolIvQPhIs9kq2itvt9aNUJcK6ag3WVGmwvlrLy61XX6pMGLDPBbFOhbORpI3A3r17ceTIEezevZvX+P379+PZZ5/Fnj17eI3/9a9/DYVCgZtvvjl0bWhoCEVF4YFNgUAArVaLoaGhqPfZvXs3VCpV6FVRUcHr+XOdIqUY3926NG33mzQA05uuTOLxc1ia5tjA6koNPukwQCZisHxKe8xKrRSdo/a4u1IAKFWLcaTbmDBYPB1TlJz86Z3LpiMU0LC4fGgbDk9N1cmFaJ2W/SMXpWfHe7TXBKVIEDqBJItSLMDKic5sGgmLs0NWHOo08Oo/EAu7x49BsxsUqGA3uC4D7G5fyBhHQyEWoLXXNGN9/kwwbHHD7cs/45QKSRmB3t5e3HPPPXjxxRchFicusbdarbjllluwZ88e6HQ6Xs947rnn0NTUxOv+8di1axfMZnPo1dvbO6P7zSW+uLYcVy0unPF9psYA4nG024iGNBqCgYn0wSGLGyf6zVhVoZrIzed4+faP9ZqxsFgBSYIMnqmwDAWbO/LeiVJvV5Srogr51ehk8EyTVhhOY2/bYWuwG1rVRNWybopMc5FChP4pO3m5SIDlZSqsr9aiVieDxeVDa68Jh7viG0r1RIP2Br0SC4pkvFpaTu1d7PEHu3gFAhw21GgjqttjyU/kAx5fACdmuerpJEmd01taWjAyMoLVq1eHrvn9fuzbtw9PPfUU3G43GObiD/LChQvo6urCDTfcELoWCASPUQKBAG1tbairqwu999FHH6GtrQ2/+93vwp5bUlKCkZHw1oQ+nw8GgwElJSVR5yoSiSASJZcrPV+gKAqP3tyIa3/2IS+JgWiwDIUlpdFdQNPxBoKpj2opi0qNFBIhA5vbh55xR1J9D6oLpChSiCIkqI/2mrG4WJ5QKmIqHn+At0sECGb7RO+rEP8u04OkQPB7Fy0OoZYK0Z3EZ+BDt8GB7omYRZFChCKFCEIBDYWIhVoW7Oc7aUyToVQlBkNRYbUMWqkQxUoRhi3RTwxykQBtUaqJbRNKrBopi+XlKoADRq2ulCufs8FnlhZjSRrcd/lAUkZg8+bNOHHiRNi122+/HfX19XjwwQfDDAAA1NfXR4x/6KGHYLVa8cQTT0S4aJ599lmsWbMGK1asCLu+ceNGmEwmtLS0YM2aNQCA9957D4FAABs2bEjmIxAmKFGJ8fBNy3Df744l/bUsE0xFTFb/3eTwwuQI/5pyjQTFChFomoLB7kH3uCOigpZlKBQpxOgad8TMn28btkVU7sZCJmRgsHmSKo5SS9moRiCeCWAZKqrGkFLMhjV3n2Sm6p+JGLG6Q3UVqyrVM1LuVE24iaZSWyiLKxG+sFget5rY6PCGVQkvL8vPRXZBkRxPf3XNrNUKmk5SRkChUKChoSHsmkwmQ0FBQej6rbfeirKyMuzevRtisThivFqtBoCI6xaLBS+//DJ+8pOfRDx3yZIluP7663HnnXfi6aefhtfrxd13340vfelL0OtTa8NGALatLMMrR/rDulUlQiigsbBIHta5aib0GZ1hQUaWobC4WAG1lIXb58eg2QWpUBC31eMkAyYn1lVrMGh2wezwwuXzo0gpRplKDKfXj1GrG06vHy6PHxIhgwWFMijELFhBUB/I6fWDoSkIGRo0TQHggm01fQFopEJUF0hBURQYChAwNJSSi8Jn0dBIhVGL2RwxXFb9RieEAjptrTtjwTIU2njURcQjmoaTxRU/xpJsAPJEvwWrK9VoG7LycvNli882lMwZAwBkQDuop6cHNJ180tHevXvBcRy+/OUvR33/xRdfxN13343NmzeDpmls374dP//5z2c63XkNRVH4txuW4vrHP+LV3FvM0qjVyWbU6CURXj8XEURdVy3lZQTcPi4i26ff6Azzf4fG2jy8paCBYN1BrFNIkUKEGp0MQxZXWO/eQoUoqhFwev1gqGDryan0mZwzbqTDh7pCeUa0pAbNLsiETMwFOxX//pEeE3RyIRYUyRPGnrLFigyn4WabGRuBDz74IO6/p/OrX/0q6vW77rorbvGXVqvFSy+9lOTsCIlYUKTAjstr8My+jrjjWIZCXaE84wtUNOhcCB9NI56RnOpmqS6QolgpRrfBAVmcNE2lhI0aL3B6/FimV+L0oCVjOvuZqsKt1EpwaiC2cRElEYifytiEwV5ZoUaPgV8BYCaZC/0PpkK0gwi4+5oFUMfJ2aYoYJlelRMDAADuDLtHeM2BZ65617gDBzsNGDK7EC9iEKtWo2PMjlMDFpRrJKjURjaMSQe2JILxyXBqwBqmYTSd8RQrhydp7TXB4/NjbVVqekTpIh9+H9MJMQIEKMQsrl8WPcsKCDY551tVmwmi5ednm1h+/HjEKyhKVF/Qa3CiUJFalW08VlWq02LMVRIBooVDoimailka62s0GElDCqzN7cfhbiPqSxSo0Ga/KTsAaOI0HZqNECNAAAD83fLSqNc31GgTNoXPNAWy3Kf62lPYPQ9FqQ+YJF5AeZJ0FklNKrumovUfjUNdRpRrpBG1AR2jdtToZFhXrcHaKg0WFMng9QVwqNMYt0NaspwdsmLQ5MSGGm1WO5GxDIUNNQWJB84iZr/6ESEtbKwtiAjqpashzEwxOXN7EqCo6B284iEXMRiKs/Plk13Sl6aaAZWERZlakvYmLV3jjqAUdY0WR3uM8Po5jNrcGLW5eQXyZ4ovEJQWX1Akh9Prj5oAkG4qNNI5lRkEkJMAYQKhgMZ1U1xCX7u0Oq1VvqkiFwlyrtRYrBQnndlSronvz+cT6x61uRP2JUhEjU4KsYDG6RmmhMYiwAX1ioqUYiwuzo3i5/kRG0bMLqypVGN9dbCHQWO5Km58IlWub4jtNp2tkJMAIcQX11bglaP9uHNTDf7vZ5cAAIQsg19+cCEn81lULIfF6c1JaiBFAQ16FSoLpFCIBNjbnJzsSKKmKBSPeuWZnsRWVahxetCccp+CZOg3OkFNNKg53meCK8vBU2+AQ0sUV1eNTgZ/gIuq9JoKV9dnrzlTtiBGgBBiQ40WD21dgh2X14Ca2Kr+63WL4fT48atPurI+l0OdhoRicOnmqsWFuHGFHlcsKoROHoxF/OFIHy6M2kBRFDiOg8cfgNPjh8Xpw5jNHTV9NFrBl0bKQiMTgqVpSIQMipUijFrdUX3/DAUc6UktFjO5GGfblcdxwT7PJUoxCuRs3HTRbNE5Zsf6ag1kIiZuf+lE0BTwna1Lsa5am8bZ5QfECBBC0DSFOzaF93ugKArf/dxSNJSp8N7ZYew7N5axFMNJsh2L0EhZXN9Qih2XV0dtFdgz7ogrOa2VslBJhZCwNMQsAxHLAByHFRUqsAwNcMGeAyNWd6g2QCkRYNjiBktTWFQsh0IswIl+c0iW2s8B6hjyEok+S5laktNYzpDFhSGLC2urNDg7ZIkqvJctVlSocLTXBHDBzKhUAuMMTeHJL6/CZ2MkT8x2iBEgJIShKXxhTTm+sKYcXn8AF0ZtONpjwgdtI3j79DDvLBYhQyfUYV9Vqc74AkZRwe5eVy0uxFWLi7C8TBU32Ddojh9wNDi8YWqby8uUCWU13BOLvTfAhap3FWIBVpSrcWbQAovLhxqdLCkjsKpCjc5xO07mqJ5jOoe7jdDJhajVyXE8ikBdiVIEUBTK1ZK0Z6AVyISoK5SjpccI/8Qv6NEeU7D3dZK/XzU62Zw1AAAxAoQkYRka9SVK1Jco8eX1leget+OJd9rxytH+mF+jkwvxr9fX43ONpTA5vDjSY8ShTgPeOzsSphu0qFiOkxny/2tlQmxaqMPVi4twxaLCpDpdRZOCjodUmPjPKlonMavLh4OdBkhYGutrtKB4OMNkQgaLSxSwuHzBHW+eMVntu7oy2EbTOqFaK6ABuZjF+REbhswuLNMrMWZ1YzhNyqGlKnGYAZjkUKcB66u1SfVV3lAz91xAU6E4bq4VQUfHYrFApVLBbDZDqcx91stc46+nhvD9P50OW9QpCvjSukr8n+vroYpSkcxxHNpHbHjg5WNwevwYsrhCi8RMYRkKqyo1uHyBDlctLkSDXjUhCpc81/zkA3SM8k95XFmhTlhcVygXJWzSIhFQaChXw+e/KG4nEtAQMEHBO4Pdg86xxE108gWtjEWlRobWPlPUhVjCMlhaqkRLirGQqVAApHF0jBrLVRi2uGLKXk/l/s8swj9vXogRiwtFUYrh8olU1jlyEiCkheuWleCqxYX4zac9+OUH57GwSIHvfm5p3K5iFEVhUbEC//uNS+H1B3Ci34x3zwzj3TMjKTVAr9HJcOWiQlyxSIcNNQWQpSG1lOM4DJqSOwnwaQ7Dpwra6eNAUxSO9ua2WC9dGOxeGOwm1Jcoou7EnV4/jvebUKaWxOjdwJ+11Zq4cZzjfWYwFLCmSg2nx49zw7aY+lDtIzYMmp24/flmvHXvFTOaVz5CTgKEtOPzB8DQVCjDKBU6x+w41DmOQ51GHO42hKlzTsLQFNZWafCZpcXYvKQYNbrEna2SxWj3YNX33+Y9XiEW8D7NJJKNlosEkApp6OQinJ5BZstso7ZQhgGjc0ZpptUF0piqr9GQCRksKJKDZWicG7aGNVtaUCSHzx+A2enF0e9dm/KcsgE5CRDyAgEz8xrEGp0MNToZ/mFdJYDg7vpQpwGHOg3w+AK4YlEhLl+gi+pmSicDCYLC06nUSnlr80iFTFwjsLhEjpZuE9y+AFZWqNDamx9SypmmY9SOxSUKjFpcSfeBBoK/O8lWLNs9/lA9CkMBjWUqUDSFU/3mUGOgYmXu5UsyATEChFlBsVKMG1boccOK7DYRStYVlEx1szCOsazUStHSbQIAmJ0+tPaasbZKk3Mdp2zRNmSFSsJiXbUGZwctsCaRZlqkEM1ItsLPIZTNpJWyWFiswNFeE6+A/2yEyEYQCHFIlB46HT7NeSaJl5ZaoooMQE7PdJnrmJ1eNHcZ4fIFsKJchZUVagiZxC5GszP500MsDA4vDnYaUKuTor4kN7IYmYYYAQIhDgNJpocmE2KLl60UbcHvNaZH+mC24fVzONZnRmuvCQxDY0FR7NiPhKXRHqWv80w5O2TDjVk+hWYLYgQIhDgMJ2kEklGYZOIEzgVR7jOZbz/HRCyTwunxR/3eTLKwSJGRE9OWJcVzUjwOIEaAQIjLsDU5I3BqwIJiBb8AYiqL+ZEeEwrloritK+c67SN2NJQpsapCFfGecIaqq9G4YYUeT3551Yyy3fKZuRnpIBDSRLzGMNFwePzQSIXQSoVJ9yDgy7DVjUXFcpwbTr/bYzbgD3A4OSHLsaJCBQFNYdjixpDZmVRRHx9+9g8rsG1l2Zw1AAAxAgRCXEZ4VJROp9/kRFWBFN5AIG7NgDeO2yKQILaglqa/9eRs5NiUtFmKQlqb0G+o0eLzq8rTdr98hbiDCIQY2N0+WFNUTO0ed6BIEd9tE4hjBBL5tc8MWrC2SgMhjzaV84V0l71+eX1lem+Yp5DfIAIhBnzkH+JxYdSOMo0Ekhh+6lgehtWV6oTKrFaXD4e7jRAyFBYWyWc0T0I4NAV8+7rFczYbaDrECBAIMeAjLpaIc8M21OhkYKPkt0fLDlpZocLJfjPAUxbO5vZDneGq6fnGzqsXYOfVC1IWHJxtkJgAgRCDmZ4EJjk9aEVDmRJtQ9awXsWTi4xIQGNJqRJefyAkDZGMa8OSxuKo+Y5ayuLOK2oTD5xDECNAIMQgXUYAAE72W1CplaJQLsKI1QUOQKVGAq1UiLNDlgjp6WTc25I5KmeQbSgK+OG25VCK59fJivz2EAgxSLaZTCJ6DI6whudChk5JMns6DB3snzD1lEFInkduasDWxrnbQSwWxAgQCDFIVjcoWdLlcm7pNkEmZLC8TAGaonCkx8i75SchyL1bFuKWS6pyPY2cQALDBEIM0n0SmI4gnhhakou43ePHkR4TDncbsaZKM7OJzTPW12hxz+aFuZ5GziBGgECIQaaNQDI6Q8mQzoKpuY5QQGP3zcvndEVwIogRIBCi4PEFMJagB/BMibfwzMSbc2HUjhqddAZ3mD/ct2UR6grnd50FMQIEQhSGLa60V6BOh45nBGb4cA2RlUhIbaEMd26qyfU0cg4xAgRCFDLtCgKAeA4IW4pyFZNkytU0l7jlkqq0tEKd7ZDvAIEQhUxnBgGx3UFyEYNe48yef7LfjNrC2M1X5jtilsbN80Acjg8zMgKPPvooKIrCvffey2v83r17QVEUtm3bFvHemTNncOONN0KlUkEmk2HdunXo6ekJvX/VVVeBoqiw1ze+8Y2ZTJ9AiElWTgIxNutLSpUzbozi9Aagk83Nxujp4IZGPVREbgPADOoEmpub8cwzz6CxsZHX+K6uLjzwwAPYtGlTxHsXLlzA5Zdfjh07duDhhx+GUqnEqVOnIBaH91m988478cgjj4T+LZWS4BchMyTbRyAVotkAhViAC6Pp6RNgcRE5iWjQFPCPV9blehp5Q0pGwGazoampCXv27MEP/n979x7V1LmmAfxJyI0AIUKIXAyigKCCF1QQT0UrVEWOdSGz6hSrMz1W65FWq13UYWrbU3umOG2nrVqtLpfi2Nrj9Kalq9Yl4q1aWgVFqXdQCypoVSARUbm884eTjDEBAiQksN/fWllL9v5IHj538mbv/e1v//3vbbZvamrCzJkz8fbbb+Onn35CTU2N2frXX38dU6ZMwXvvvWdaFhpq+Z+kVCrh798zb/HGXEtDU7PDX+PxPQGpWIRgHyVOXdPb5fnPVhkwtI83TlypbbuxgDw9NBBhPPOqSYcOB2VkZCAlJQVJSUk2tV++fDm0Wi3mzJljsa65uRk//PADBgwYgEmTJkGr1SIuLg47duywaLt161ZoNBpERUUhKysLd++2fOPt+/fvQ6/Xmz0Ys9WixHCoFI69oF70yL6An6ccoVpPuxUAowvXDQj24T1mIzexCC9NEO6FYda0uwhs27YNx44dQ3Z2tk3tDx06hI0bN2LDhg1W19+4cQN37tzBihUrMHnyZOzevRupqamYPn06Dhw4YGqXnp6Ozz//HPv27UNWVhY+++wzPPfccy2+bnZ2Nry9vU0PnU7Xvj+UCZpWpcD6WSMhd+BNW8QiIMzPA7H9fHDnQSPOVhns/hp3G5rh49H6cNFAb0Wr63uSVxLDeS/gMe36qlNRUYFFixYhLy/P4ni9NQaDAbNmzcKGDRug0WistmlufrjbPW3aNCxevBgAMGzYMPz8889Yt24dxo0bBwCYN2+e6Xeio6MREBCAxMRElJWVWT10lJWVhSVLlph+1uv1XAhYu8SH+mL9rBGYu6XQIZOzEYDSP+oAO98X93HVLVxB7KWQYN7Y/nhudF/M/7wIv1667dAczrY4aQBemhDm7Bgup11FoKioCDdu3EBMTIxpWVNTEw4ePIhPPvkE9+/fh5vb/99Or6ysDJcvX8bUqVNNy4wf+hKJBOfOnYNOp4NEIsGgQYPMXmvgwIE4dOhQi1ni4uIAAKWlpVaLgFwuh1zOoyNY54yP0OKT9Bi8/I/jeNBo3/MEXTWS/2rNXXi7S1H7yH0HkqP88fbTg6FVPfwyt/WFOKzdX4aV+Rc6PTLJFb3x50GY8wRfGGZNu4pAYmIiSkpKzJY9//zziIyMxNKlS80KAABERkZatF+2bBkMBgNWrlwJnU4HmUyGUaNG4dy5c2btzp8/j759W57Vr7i4GAAQECC8qV9Z15o02B+7Fo1F1rcldv623DVloLEZCNN6ouj3ami95Fg+LQqTo8wHWEjcxFiYGI5RIT6YtfFXNPagQjAl2h9/+VOIs2O4rHYVAS8vL0RFRZkt8/DwgK+vr2n57NmzERQUhOzsbCgUCov2arUaAMyWZ2ZmYsaMGUhISMCTTz6JXbt24fvvv8f+/fsBPNyj+OKLLzBlyhT4+vri5MmTWLx4MRISEmweospYZ/T388Q/5o7G/xRW4N2dZ2C417kregE4rAa4iUUW3+blEjEWjA/FgifD4Clv+W0fH+qLlyeE46M95x0TrotF+nshe/oQQU8Q1xa7D38oLy+HWNy+k2mpqalYt24dsrOzsXDhQkREROCbb77BE088AQCQyWTYs2cPPv74Y9TV1UGn0yEtLQ3Lli2zd3zGWiQWi/BsbDASI7XI+OIYjl6u7tTzOeJjaahOjQ2zR6DocjX+fXsJqu82IGVIAJZOikCwr21XEC9MDEOAWoHl35/u9PQVztTXV4ktc2Lh7c4XhbVGRJ2dqaqb0Ov18Pb2Rm1tLVQqlbPjsG7ut6u1+PPqls9Z2SKun49dDy+NDddgzcwY0+0Rb9c9gOFeA/ra+OH/uNt1D/DXbnrCOEzriZx/HQWdwIbHduRzjucOYqwDooK8MW6AX5e81rOxOiycEIbU4UFQK6VQSC3ftl4KCVakDTG7P66Ph6zDBcD4+1vmxGJ8RNf8nfYyY6QOuS/9SXAFoKP49pKMddCUaH8cOP+HQ18jPS4Y76ZGmy1rbiYUlVfj68Ir+KGkEpH+XvhoxjAEqd3t/vpyiRvWzxqBzK9OIvfENbs/v709M7IP/vOf+Dxhe3ARYKyDgtSd+6bZ1nFYrZfc6rBGsViEUSE+GBXig+zp0RA7eNpoucQNK/95GGrrGxxe9DprdnyIsyN0O1wEGOug4cFq/PdfYlFb34Dfrtbi57KbOH1Nb5ebvL84rj+eH9MP/m1czevoAmAkEomwdmYM5n1WiMOlt7rkNdsrKkiFqCBvZ8fodrgIMNZBHnKJ6bzA00MDATycubPocjV+uXQLV6vr0UspQy+lFM0EGO414OLNOvx04SYAy9FBQWp3BPVyx/NjQpAc7XrXv3jIJdj4L6Mwa+OvnR4Z5QgzRvKMAB3BRYAxO1IppHgyUosnI7VW1xMRPt5zASvzL4AAhPp5IHV4EKYODezUSdyuopC64bM5cXj1qxP44WSls+OYmTiYZxjuCC4CjHUhkUiExU8NgL+3AnKpGNOGBnW7W0EqpG745NnhGK5T4+M9F0zXEohFD89zOGPQeaifB3qrhDMRnj1xEWDMCZ6NDXZ2hE4RiUR4YWx/pMX0wfqDF/HtsSt4aUIYBgWo8MWv5Th44Q/cvGN94jpH6O/HM4N2FBcBxliH9fKQ4d+SI5E5KcK0RzMyxAfNzYSTV2ux4aeL2FlS6fC9AzeeFqLD+GIxxlinPX5ISywWYZhOjTXpMdj76njMjm95Mkh7uFLT8g2mWOu4CDDGHKqfxgNvPz0YU/9vBJUj/HZVjwvX7X9THiHgw0GMMYcTiUT4j9QolFypweVbjvnWvnZ/GcK0ngj2UaKZCGPD/dq8qxrjCeQYY13IcK8B/7X7PLYUXLbLRXWtGRSgwvpZI+AhlwimGHTkc46LAGOsy12+WYc9Z67jwPk/cOqaHrdbuAVmR3jI3DDA3wtSNzHGhmnw1/GhkLgJ48g3F4FWcBFgzHVdq6nHLxdvoaDsFgou3sKV6vpW23vI3NDLQwYvhRT9NR6I8PdCX18lYoJ7IVDt3u2uvbAXLgKt4CLAWPdRVXsPRb9Xo7K2HlqVAoHeCngqJPBSSOHrIYNC6tb2kwhQRz7n+MQwY8zl+HsrkDLE9eZP6omEcaCMMcaYVVwEGGNMwLgIMMaYgHERYIwxAeMiwBhjAsZFgDHGBIyLAGOMCRgXAcYYEzAuAowxJmBcBBhjTMC4CDDGmIBxEWCMMQHjIsAYYwLGRYAxxgRMMFNJG2+boNfrnZyEMcYcw/j51p7bxAimCBgMBgCATqdzchLGGHMsg8EAb29vm9oK5s5izc3NuHbtGry8vCASdezWc3q9HjqdDhUVFd3m7mTdMTPAubtSd8wMcG5riAgGgwGBgYEQi2072i+YPQGxWIw+ffrY5blUKlW32uiA7pkZ4NxdqTtmBjj342zdAzDiE8OMMSZgXAQYY0zAuAi0g1wux1tvvQW5XO7sKDbrjpkBzt2VumNmgHPbi2BODDPGGLPEewKMMSZgXAQYY0zAuAgwxpiAcRFgjDEB67FFYMWKFRCJRHjllVcAALdv38bLL7+MiIgIuLu7Izg4GAsXLkRtba3Z74lEIovHtm3bzNrs378fMTExkMvlCAsLw+bNmy1ef82aNQgJCYFCoUBcXByOHDlitv7evXvIyMiAr68vPD09kZaWhuvXr1vkBoAXX3wRoaGhcHd3h5+fH6ZNm4azZ8+aPV95eTlSUlKgVCqh1WqRmZmJxsbGLsm9bNmyDmV2xb42IiIkJydDJBJhx44dLtPXncntzP62to2MHz/eIs/8+fNdvq9tye3sbbtdqAc6cuQIhYSE0JAhQ2jRokVERFRSUkLTp0+n3NxcKi0tpfz8fAoPD6e0tDSz3wVAOTk5VFlZaXrU19eb1l+8eJGUSiUtWbKETp8+TatXryY3NzfatWuXqc22bdtIJpPRpk2b6NSpUzR37lxSq9V0/fp1U5v58+eTTqej/Px8KiwspNGjR1N0dLRFbiKi9evX04EDB+jSpUtUVFREU6dOJZ1OR42NjURE1NjYSFFRUZSUlETHjx+nnTt3kkajoaysLIfnjoqKIrlc3u7MrtrXRh9++CElJycTANq+fbtpuTP7ujO5ndnfLW0j48aNo7lz55rlqa2tdfm+biu3M/t69OjRNGbMGIvtojU9rggYDAYKDw+nvLw8GjdunNU3itGXX35JMpmMGhoaTMusvXke9dprr9HgwYPNls2YMYMmTZpk+jk2NpYyMjJMPzc1NVFgYCBlZ2cTEVFNTQ1JpVL66quvTG0KCwsJAK1cubLN3CdOnCAAVFpaSkREO3fuJLFYTFVVVaY2n376KalUKrp//77DchsMBurbty8BoOHDh7crM5Hr9vXx48cpKCiIKisrLTI6q687m5vIOf3d2jbS1nbuqn3dVm4i523bZ86cIQBUUFDQar5H9bjDQRkZGUhJSUFSUlKbbWtra6FSqSCRmE+hlJGRAY1Gg9jYWGzatMlsWtaCggKL5540aRIKCgoAAA8ePEBRUZFZG7FYjKSkJFOboqIiNDQ0mLVZtWoVvLy80NTU1Grmuro65OTkoF+/fqYZUQsKChAdHY3evXubZdLr9Th16pTDcmdkZCA1NRXBwcGtTtFtLbORq/X13bt3kZ6ejjVr1sDf399ivbP6urO5jbq6v9vaRrZu3QqNRoOoqChkZWXh7t27Znlcsa/bym3kjG07MjISwcHBpja26FETyG3btg3Hjh3D0aNH22x78+ZNvPPOO5g3b57Z8uXLl2PChAlQKpXYvXs3FixYgDt37mDhwoUAgKqqKrONEgB69+4NvV6P+vp6VFdXo6mpyWob4zHxqqoqyGQyqNVqs9wDBgxAVVWV1bxr167Fa6+9hrq6OkRERCAvLw8ymazVTMZ1jsj9aF8fPnzYau7WMrtqXy9evBhjxozBtGnTLNa1lsm4zlVzA13f321tI+np6ejbty8CAwNx8uRJLF26FOfOncO3337r0n3dVm5n9PXjbVr6HLGmxxSBiooKLFq0CHl5eVAoFK221ev1SElJwaBBg/C3v/3NbN0bb7xh+vfw4cNRV1eH999/3/SfZ2+P5n7hhRdabDdz5kw89dRTqKysxAcffIBnnnkGhw8fbvNvdQRb+7qtzK7W17m5udi7dy+OHz/ukNfvKHvl7sr+tmUbefQLWHR0NAICApCYmIiysjKEhobaPZMtbHk/2pK7q7ftzugxh4OKiopw48YNxMTEQCKRQCKR4MCBA1i1ahUkEolpt85gMGDy5Mnw8vLC9u3bIZVKW33euLg4XLlyBffv3wcA+Pv7W5x9v379OlQqFdzd3aHRaODm5ma1jXE33d/fHw8ePEBNTY1Z7qNHj+KDDz6wmtvb2xvh4eFISEjA119/jbNnz2L79u2tZjKus3fugwcPmvX10aNHUVFR0a7MrtjXeXl5KCsrg1qtNm1DAJCWlobx48c7pa/tlbur+9vWbeTxPABQWlrqsn1tS25rHL1tt9TGFj2mCCQmJqKkpATFxcWmx8iRIzFz5kwUFxfDzc0Ner0eEydOhEwmQ25urk3foouLi9GrVy/TZE/x8fHIz883a5OXl4f4+HgAgEwmw4gRI8zaNDc3Iz8/39RmxIgRkEqlyM/PN+U2fjhu2bLFIvfj6OEJfdMGFR8fj5KSEty4ccMsk0qlwqBBg+yem4hMfW3MPXDgwHZldsW+fv3113Hy5EmzbQgAPvroI+Tk5Dilr+2Vu6v7uyPbiDF3QECAy/a1LbmtcfS2bXTu3DmUl5eb2tjE5lPI3dCjZ/Fra2spLi6OoqOjqbS01GzolnHYYm5uLm3YsIFKSkrowoULtHbtWlIqlfTmm2+antM4tCszM5POnDlDa9assTq0Sy6X0+bNm+n06dM0b948UqvVZqMc5s+fT8HBwbR3714qLCyk+Ph4io+Pt8hdVlZG7777LhUWFtLvv/9Ohw8fpqlTp5KPj49pqJhxKN3EiROpuLiYdu3aRX5+flaH0jkqd3szu2JfW4MWhog6s687ktsV+vvRzKWlpbR8+XIqLCykS5cu0XfffUf9+/enhIQEl+5rW3K7Ql+3h2CKwL59+wiA1celS5eIiOjHH3+kYcOGkaenJ3l4eNDQoUNp3bp11NTUZPa8+/bto2HDhpFMJqP+/ftTTk6OxWuvXr2agoODSSaTUWxsLP3yyy9m6+vr62nBggXUq1cvUiqVlJqaSpWVlRa5r169SsnJyaTVakkqlVKfPn0oPT2dzp49a/Z8ly9fpuTkZHJ3dyeNRkOvvvqq2dBXR+dub2ZX7GtrHv8wdYW+7khuV+jvRzOXl5dTQkIC+fj4kFwup7CwMMrMzLQYb+9qfW1Lblfo6/bgqaQZY0zAesw5AcYYY+3HRYAxxgSMiwBjjAkYFwHGGBMwLgKMMSZgXAQYY0zAuAgwxpiAcRFgjDEB4yLAGGMCxkWAMcYEjIsAY4wJGBcBxhgTsP8F3xpj0Z0BEFUAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Those are the Madrid's polygon districts\n",
    "districts = gpd.read_file(\"barrios/Barrios_Madrid_ETRS89.shp\")\n",
    "districts.plot()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Geocoding tasks</h3>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "houses = pd.read_csv('datasets/base_data/houses_Madrid.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 24/21742 [00:23<6:03:12,  1.00s/it]RateLimiter caught an error, retrying (0/2 tries). Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter caught an error, retrying (1/2 tries). Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter swallowed an error after 2 retries. Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      " 51%|█████     | 10993/21742 [3:04:03<3:23:20,  1.14s/it]RateLimiter caught an error, retrying (0/2 tries). Called with (*('paseo de San Francisco de Sales, Vallehermoso, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 475, in _request\n",
      "    raise AdapterHTTPError(\n",
      "geopy.adapters.AdapterHTTPError: Non-successful status code 502\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 388, in _call_geocoder\n",
      "    res = self._adapter_error_handler(error)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 411, in _adapter_error_handler\n",
      "    raise exc_cls(str(error)) from error\n",
      "geopy.exc.GeocoderServiceError: Non-successful status code 502\n",
      " 60%|█████▉    | 12950/21742 [3:36:50<2:26:19,  1.00it/s]RateLimiter caught an error, retrying (0/2 tries). Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter caught an error, retrying (1/2 tries). Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter swallowed an error after 2 retries. Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      " 61%|██████▏   | 13356/21742 [3:43:56<2:20:09,  1.00s/it] RateLimiter caught an error, retrying (0/2 tries). Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter caught an error, retrying (1/2 tries). Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter swallowed an error after 2 retries. Called with (*('calle de Fernando Gabriel, 7, Pueblo Nuevo, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+Fernando+Gabriel%2C+7%2C+Pueblo+Nuevo%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      " 98%|█████████▊| 21211/21742 [5:55:32<08:43,  1.01it/s]   RateLimiter caught an error, retrying (0/2 tries). Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter caught an error, retrying (1/2 tries). Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "RateLimiter swallowed an error after 2 retries. Called with (*('calle de las Islas, San Andrés, Madrid',), **{}).\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 536, in _make_request\n",
      "    response = conn.getresponse()\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connection.py\", line 454, in getresponse\n",
      "    httplib_response = super().getresponse()\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 1375, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 318, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py\", line 279, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1278, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py\", line 1134, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "TimeoutError: The read operation timed out\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n",
      "    response = self._make_request(\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 538, in _make_request\n",
      "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 370, in _raise_timeout\n",
      "    raise ReadTimeoutError(\n",
      "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 486, in send\n",
      "    resp = conn.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n",
      "    return self.urlopen(\n",
      "           ^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n",
      "    retries = retries.increment(\n",
      "              ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n",
      "    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 457, in _request\n",
      "    resp = self.session.get(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 602, in get\n",
      "    return self.request(\"GET\", url, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 519, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 136, in _retries_gen\n",
      "    yield i  # Run the function.\n",
      "    ^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/extra/rate_limiter.py\", line 274, in __call__\n",
      "    res = self.func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/nominatim.py\", line 297, in geocode\n",
      "    return self._call_geocoder(url, callback, timeout=timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/geocoders/base.py\", line 368, in _call_geocoder\n",
      "    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 447, in get_json\n",
      "    resp = self._request(url, timeout=timeout, headers=headers)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/lgfresh/Desktop/prac2/.venv/lib/python3.11/site-packages/geopy/adapters.py\", line 469, in _request\n",
      "    raise GeocoderUnavailable(message)\n",
      "geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=calle+de+las+Islas%2C+San+Andr%C3%A9s%2C+Madrid&format=json&limit=1 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)\"))\n",
      "100%|██████████| 21742/21742 [6:04:43<00:00,  1.01s/it]  \n"
     ]
    }
   ],
   "source": [
    "# Geocoding for lat-long using open street maps\n",
    "nominatim_service = Nominatim(user_agent='luis.gfresno@gmail.com')\n",
    "geocode = RateLimiter(nominatim_service.geocode, min_delay_seconds=1)\n",
    "geocoding_list = list()\n",
    "total_count = 0\n",
    "error_count = 0\n",
    "for x in tqdm(range(len(houses))):\n",
    "    aux_dict = dict()\n",
    "    aux_dict['full_title'] = houses['full_title'][x]\n",
    "    try:\n",
    "        response = geocode(houses['full_title'][x])\n",
    "        aux_dict['latitude'] = response.latitude\n",
    "        aux_dict['longitude'] = response.longitude\n",
    "        geocoding_list.append(aux_dict)\n",
    "        total_count += 1\n",
    "    except Exception as e:\n",
    "        error_count += 1\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "geocoding_dataframe = pd.DataFrame(geocoding_list)\n",
    "geocoding_dataframe.to_csv('datasets/geocoding/houses_geocoding_from_osmaps.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "13988\n",
      "7754\n",
      "0.6433630760739583\n"
     ]
    }
   ],
   "source": [
    "print(total_count)\n",
    "print(error_count)\n",
    "print(total_count/(total_count+error_count))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Geocoding for zip_codes using google maps free api\n",
    "google_api = 'AIzaSyBLOGyjG4y0vsmeAheUF0JP-1pAYLZltXo'\n",
    "unique_districts = houses['subtitle'].unique()\n",
    "zip_code_list = list()\n",
    "gmaps = googlemaps.Client(key=google_api)\n",
    "for x in tqdm(range(len(unique_districts))):\n",
    "    aux_dict = dict()\n",
    "    aux_dict['subtitle'] = unique_districts[x]\n",
    "    try:\n",
    "        response = gmaps.geocode(unique_districts[x])\n",
    "        zip_code = 0\n",
    "        for c in range(len(response[0]['address_components'])):\n",
    "            for t in range(len(response[0]['address_components'][c]['types'])):\n",
    "                if response[0]['address_components'][c]['types'][t] == 'postal_code':\n",
    "                    zip_code = int(response[0]['address_components'][c]['long_name'])\n",
    "        aux_dict['postal_code'] = zip_code\n",
    "        zip_code_list.append(aux_dict)\n",
    "        total_count += 1\n",
    "    except Exception as e:\n",
    "        error_count += 1\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "zip_code_df = pd.DataFrame(zip_code_list)\n",
    "zip_code_df.to_csv('datasets/geocoding/houses_zip_code_from_gmaps.csv')"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Dimensionality Reduction and Subsampling</h3>\n",
    "<h4>PCA</h4>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 365,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "buy_price                             1.000000\n",
      "sq_mt_built                           0.859708\n",
      "n_bathrooms                           0.750374\n",
      "price_per_m2                          0.652086\n",
      "n_rooms                               0.485201\n",
      "hosts_distribution_per_zip_code       0.344046\n",
      "has_lift                              0.340392\n",
      "has_parking                           0.297601\n",
      "zip_codes_count                       0.097779\n",
      "hosts_count_per_zip_code              0.078138\n",
      "average_reviews_per_month_per_code   -0.036218\n",
      "zip_code                             -0.324767\n",
      "rent_price                           -0.456933\n",
      "buy_for_rent_ratio                   -0.478690\n",
      "Name: buy_price, dtype: float64\n"
     ]
    }
   ],
   "source": [
    "from sklearn.decomposition import PCA\n",
    "\n",
    "\n",
    "# Load scikit learn's PCA\n",
    "pca_algo = PCA(n_components=5) #\n",
    "\n",
    "analysis_df = clean_houses_df[['sq_mt_built', 'n_rooms',\\\n",
    "    'n_bathrooms', 'rent_price',\\\n",
    "    'buy_price', 'has_lift', 'has_parking',\\\n",
    "    'zip_code',\\\n",
    "    'zip_codes_count', 'price_per_m2', 'hosts_count_per_zip_code',\n",
    "    'hosts_distribution_per_zip_code', 'average_reviews_per_month_per_code',\\\n",
    "    'buy_for_rent_ratio']]\n",
    "analysis_df = analysis_df.applymap(lambda x: '0' if x == 'None' else x)\n",
    "analysis_df = analysis_df.applymap(lambda x: '0' if x == 'NaN' else x)\n",
    "analysis_df.dropna(how='all', axis=0, inplace=True)\n",
    "print(analysis_df.corr()['buy_price'].sort_values(ascending=False))\n",
    "analysis_df.head()\n",
    "analysis_df['has_lift'] = analysis_df['has_lift'].fillna(0)\n",
    "analysis_df['n_bathrooms'] = analysis_df['n_bathrooms'].fillna(0)\n",
    "\n",
    "# pca_df = clean_houses_df[pca_list]\n",
    "# print(pca_df.shape)\n",
    "# pca_df.dropna(axis=0, inplace=True)\n",
    "# print(pca_df.shape)\n",
    "# print(pca_df['floor'].unique())\n",
    "# out_df = pca_algo.fit_transform(analysis_df)\n",
    "# print(out_df)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
